FCFLAGS=-qoverride-limits -convert big_endian -assume byterecl -align array64byte,all -traceback -fpic -qopenmp \
  -qopenmp-threadprivate compat -fp-model source -qopt-report=5 -qopt-report-phase=vec -ftz -diag-disable=remark,cpu-dispatch \
  -g -O0 -march=core-avx2 -finline-functions -finline-limit=500 -Winline -qopt-prefetch=4 -fast-transcendentals -fimf-use-svml -no-fma -r8

CCFLAGS=-std=c++11 -O0 -no-fma -fpic -traceback -align

ARCH=cpu_intel_d
LIBS=

FC=fxtran-f90 \
  --prefix fxtran-acdc \
  --user-directory-in user-in \
  --user-directory-out user-out \
  --config $(SRC)/fxtran.conf -- \
  ifort \
  $(FCFLAGS) -DARCH="'$(ARCH)'"

boot: fxtran-acdc

fxtran-acdc:
	fxtran-boot --prefix fxtran-acdc\
               --F90  "ifort $(FCFLAGS)"\
               --CXX "icx $(CCFLAGS)"

CC=icc -qopenmp
