FCFLAGS=-qoverride-limits -convert big_endian -assume byterecl -align array64byte,all -traceback -fpic -qopenmp \
  -qopenmp-threadprivate compat -fp-model source -qopt-report=5 -qopt-report-phase=vec -ftz -diag-disable=remark,cpu-dispatch \
  -g -O2 -march=core-avx2 -finline-functions -finline-limit=500 -Winline -qopt-prefetch=4 -fast-transcendentals -fimf-use-svml -no-fma -r8

CCFLAGS=-qoverride-limits -align -traceback -fpic -qopenmp -qopenmp -fp-model source -no-fma -g -O0 -fp-stack-check

ARCH=cpu_intel_d
LIBS=

FC=fxtran-f90 \
  --prefix fxtran-acdc \
  --user-directory-in user-in \
  --user-directory-out user-out \
  --config $(SRC)/fxtran.conf -- \
  ifort \
  $(FCFLAGS) -DARCH="'$(ARCH)'"

boot: fxtran-acdc

fxtran-acdc:
	fxtran-boot --prefix fxtran-acdc --  ifort $(FCFLAGS)

CC=icc -qopenmp
