
MODULE MODE_COMPUTE_MF_CLOUD_OPENACC


IMPLICIT NONE


CONTAINS
SUBROUTINE COMPUTE_MF_CLOUD_OPENACC (D, CST, TURBN, PARAMMF, ICEP, OSTATNW, KRR, KRRL&
&, KRRI, PFRAC_ICE, PRV_UP, PRC_UP, PRI_UP, PEMF, PTHL_UP, PRT_UP, PFRAC_UP, PTH_UP,&
& PEXNM, PTHLM, PRTM, PTHM, PRM, PDZZ, KKLCL, PPABSM, PRHODREF, PRC_MF, PRI_MF, PCF_MF&
&, PSIGMF, PHLC_HRC, PHLC_HCF, PHLI_HRI, PHLI_HCF, PWEIGHT_MF_CLOUD, YDSTACK)
!$ACC ROUTINE (COMPUTE_MF_CLOUD_OPENACC) SEQ
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODD_CST,ONLY:CST_T
USE MODD_TURB_N,ONLY:TURB_T
USE MODD_PARAM_MFSHALL_N,ONLY:PARAM_MFSHALL_T
USE MODD_RAIN_ICE_PARAM_N,ONLY:RAIN_ICE_PARAM_T
USE MODE_MSG,ONLY:PRINT_MSG, NVERB_FATAL
USE MODE_COMPUTE_MF_CLOUD_DIRECT_OPENACC,ONLY:COMPUTE_MF_CLOUD_DIRECT_OPENACC
USE MODE_COMPUTE_MF_CLOUD_STAT_OPENACC,ONLY:COMPUTE_MF_CLOUD_STAT_OPENACC
USE MODE_COMPUTE_MF_CLOUD_BIGAUS_OPENACC,ONLY:COMPUTE_MF_CLOUD_BIGAUS_OPENACC

#include "stack.h"
USE STACK_MOD
USE ABOR1_ACC_MOD

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
TYPE (CST_T), INTENT (IN)::CST
TYPE (TURB_T), INTENT (IN)::TURBN
TYPE (PARAM_MFSHALL_T), INTENT (IN)::PARAMMF
TYPE (RAIN_ICE_PARAM_T), INTENT (IN)::ICEP
INTEGER, INTENT (IN)::KRR
INTEGER, INTENT (IN)::KRRL
INTEGER, INTENT (IN)::KRRI
LOGICAL, INTENT (IN)::OSTATNW
REAL, INTENT (IN)::PFRAC_ICE(D%NIJT, D%NKT)
REAL, INTENT (IN)::PEMF(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRI_UP(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRC_UP(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRV_UP(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRT_UP(D%NIJT, D%NKT)
REAL, INTENT (IN)::PTHL_UP(D%NIJT, D%NKT)
REAL, INTENT (IN)::PFRAC_UP(D%NIJT, D%NKT)
REAL, INTENT (IN)::PTH_UP(D%NIJT, D%NKT)
REAL, INTENT (IN)::PEXNM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRTM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PTHLM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PTHM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRM(D%NIJT, D%NKT, KRR)
REAL, INTENT (IN)::PDZZ(D%NIJT, D%NKT)
INTEGER, INTENT (IN)::KKLCL(D%NIJT)
REAL, INTENT (IN)::PRHODREF(D%NIJT, D%NKT)
REAL, INTENT (IN)::PPABSM(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PRI_MF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PRC_MF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PCF_MF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PSIGMF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PHLI_HCF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PHLI_HRI(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PHLC_HCF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PHLC_HRC(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PWEIGHT_MF_CLOUD(D%NIJT, D%NKT)
TYPE(STACK), INTENT (IN) :: YDSTACK
TYPE(STACK) :: YLSTACK

INTEGER :: JI

YLSTACK = YDSTACK



JI = D%NIB


PRC_MF (JI,:)=0.
PRI_MF (JI,:)=0.
PCF_MF (JI,:)=0.
PSIGMF (JI,:)=0.
PHLC_HCF (JI,:)=0.
PHLC_HRC (JI,:)=0.
PHLI_HCF (JI,:)=0.
PHLI_HRI (JI,:)=0.
PWEIGHT_MF_CLOUD (JI,:)=0.

IF (PARAMMF%CMF_CLOUD=='DIRE') THEN
  CALL COMPUTE_MF_CLOUD_DIRECT_OPENACC (D, PARAMMF, KKLCL, PFRAC_UP, PRC_UP&
  &, PRI_UP, PRC_MF, PRI_MF, PCF_MF, PWEIGHT_MF_CLOUD, YDSTACK=YLSTACK)
ELSEIF (PARAMMF%CMF_CLOUD=='STAT') THEN
  CALL COMPUTE_MF_CLOUD_STAT_OPENACC (D, CST, TURBN, PARAMMF, KRR, KRRL, KRRI, OSTATNW, PFRAC_ICE,&
  & PTHLM, PRTM, PPABSM, PRM, PDZZ, PTHM, PEXNM, PEMF, PTHL_UP, PRT_UP, PSIGMF, YDSTACK=YLSTACK)
ELSEIF (PARAMMF%CMF_CLOUD=='BIGA') THEN
  CALL COMPUTE_MF_CLOUD_BIGAUS_OPENACC (D, CST, PARAMMF, ICEP, KRR, PRT_UP, PRV_UP, PRC_UP, PRI_UP&
  &, PTH_UP, PFRAC_UP, PRTM, PTHM, PRM, PRHODREF, PEXNM, PPABSM, PRC_MF, PRI_MF, PCF_MF, PSIGMF&
  &, PHLC_HRC, PHLC_HCF, PHLI_HRI, PHLI_HCF, PWEIGHT_MF_CLOUD, YDSTACK=YLSTACK)
ELSEIF (PARAMMF%CMF_CLOUD=='NONE') THEN
ELSE
  CALL ABOR1_ACC ('Shallow convection cloud scheme not valid: PARAMMF%CMF_CLOUD='//PARAMMF%CMF_CLOUD)
ENDIF



ENDSUBROUTINE COMPUTE_MF_CLOUD_OPENACC

ENDMODULE MODE_COMPUTE_MF_CLOUD_OPENACC
