
MODULE MODE_COMPUTE_MF_CLOUD_DIRECT_OPENACC


IMPLICIT NONE



CONTAINS
SUBROUTINE COMPUTE_MF_CLOUD_DIRECT_OPENACC (D, PARAMMF, KKLCL, PFRAC_UP&
&, PRC_UP, PRI_UP, PRC_MF, PRI_MF, PCF_MF, PWEIGHT_MF_CLOUD, YDSTACK)
!$ACC ROUTINE (COMPUTE_MF_CLOUD_DIRECT_OPENACC) SEQ
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODD_PARAM_MFSHALL_N,ONLY:PARAM_MFSHALL_T
USE MODE_SHUMAN_MF_OPENACC,ONLY:MZF_MF_OPENACC

#include "stack.h"
USE STACK_MOD
USE ABOR1_ACC_MOD

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
TYPE (PARAM_MFSHALL_T), INTENT (IN)::PARAMMF
INTEGER, INTENT (IN)::KKLCL(D%NIJT)
REAL, INTENT (IN)::PFRAC_UP(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRI_UP(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRC_UP(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PRI_MF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PRC_MF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PCF_MF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PWEIGHT_MF_CLOUD(D%NIJT, D%NKT)
TYPE(STACK), INTENT (IN) :: YDSTACK
TYPE(STACK) :: YLSTACK

INTEGER::IIJE
INTEGER::IIJB
INTEGER::IKT
INTEGER::IKL
INTEGER::IKE
INTEGER::IKB
INTEGER::JK0
INTEGER::JK
INTEGER::JI
temp (REAL, ZFRAC_UP_M, (D%NIJT, D%NKT))

YLSTACK = YDSTACK



IF (KIND (ZFRAC_UP_M) == 8) THEN
    alloc8 (ZFRAC_UP_M)
ELSEIF (KIND (ZFRAC_UP_M) == 4) THEN
    alloc4 (ZFRAC_UP_M)
ELSE
    STOP 1
ENDIF


JI = D%NIB


IKB=D%NKB
IKE=D%NKE
IKL=D%NKL
IKT=D%NKT
IIJB=D%NIJB
IIJE=D%NIJE
PRC_MF (JI,:)=0.
PRI_MF (JI,:)=0.
PCF_MF (JI,:)=0.

IF (PARAMMF%LRELAX_ALPHA_MF) THEN
  CALL MZF_MF_OPENACC (D, PFRAC_UP, ZFRAC_UP_M, YDSTACK=YLSTACK)

  DO JK=1, IKT
    
    PWEIGHT_MF_CLOUD (JI, JK)=ZFRAC_UP_M (JI, JK)*PARAMMF%XALPHA_MF
    PWEIGHT_MF_CLOUD (JI, JK)=MAX (0., MIN (PWEIGHT_MF_CLOUD (JI, JK), 1.))
  
  ENDDO

ENDIF


JK0=KKLCL (JI)-IKL
JK0=MAX (JK0, MIN (IKB, IKE))
JK0=MIN (JK0, MAX (IKB, IKE))

DO JK=JK0, IKE-IKL, IKL
  PCF_MF (JI, JK)=MAX (0., MIN (1., PARAMMF%XKCF_MF*0.5*(PFRAC_UP (JI, JK)+PFRAC_UP (JI, JK+IKL))))
  PRC_MF (JI, JK)=0.5*PARAMMF%XKCF_MF*(PFRAC_UP (JI, JK)*PRC_UP&
  & (JI, JK)+PFRAC_UP (JI, JK+IKL)*PRC_UP (JI, JK+IKL))
  PRI_MF (JI, JK)=0.5*PARAMMF%XKCF_MF*(PFRAC_UP (JI, JK)*PRI_UP&
  & (JI, JK)+PFRAC_UP (JI, JK+IKL)*PRI_UP (JI, JK+IKL))
ENDDO



ENDSUBROUTINE COMPUTE_MF_CLOUD_DIRECT_OPENACC

ENDMODULE MODE_COMPUTE_MF_CLOUD_DIRECT_OPENACC
