
MODULE MODE_MF_TURB_OPENACC


IMPLICIT NONE


CONTAINS
SUBROUTINE MF_TURB_OPENACC (D, KSV, PARAMMF, ONOMIXLG, KSV_LGBEG, KSV_LGEND, PTSTEP, PDZZ&
&, PRHODJ, PTHLM, PTHVM, PRTM, PUM, PVM, PSVM, PTKEM, PTHLDT, PRTDT, PUDT, PVDT, PSVDT,&
& PTKEDT, PEMF, PTHL_UP, PTHV_UP, PRT_UP, PU_UP, PV_UP, PSV_UP, PTKE_UP, PFLXZTHMF, PFLXZTHVMF&
&, PFLXZRMF, PFLXZUMF, PFLXZVMF, PFLXZSVMF, PFLXZTKEMF, PFRAC_UP, YDSTACK)
!$ACC ROUTINE (MF_TURB_OPENACC) SEQ
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODD_PARAM_MFSHALL_N,ONLY:PARAM_MFSHALL_T
USE MODE_SHUMAN_MF_OPENACC,ONLY:MZM_MF_OPENACC
USE MODE_TRIDIAG_MASSFLUX_OPENACC,ONLY:TRIDIAG_MASSFLUX_OPENACC

#include "stack.h"
USE STACK_MOD
USE ABOR1_ACC_MOD

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
INTEGER, INTENT (IN)::KSV
TYPE (PARAM_MFSHALL_T), INTENT (IN)::PARAMMF
LOGICAL, INTENT (IN)::ONOMIXLG
INTEGER, INTENT (IN)::KSV_LGBEG
INTEGER, INTENT (IN)::KSV_LGEND
REAL, INTENT (IN)::PTSTEP
REAL, INTENT (IN)::PDZZ(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRHODJ(D%NIJT, D%NKT)
REAL, INTENT (IN)::PTHLM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRTM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PTHVM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PUM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PVM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PSVM(D%NIJT, D%NKT, KSV)
REAL, INTENT (IN)::PTKEM(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PTHLDT(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PRTDT(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PUDT(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PVDT(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PSVDT(D%NIJT, D%NKT, KSV)
REAL, INTENT (OUT)::PTKEDT(D%NIJT, D%NKT)
REAL, INTENT (IN)::PTKE_UP(D%NIJT, D%NKT)
REAL, INTENT (IN)::PV_UP(D%NIJT, D%NKT)
REAL, INTENT (IN)::PU_UP(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRT_UP(D%NIJT, D%NKT)
REAL, INTENT (IN)::PTHV_UP(D%NIJT, D%NKT)
REAL, INTENT (IN)::PTHL_UP(D%NIJT, D%NKT)
REAL, INTENT (IN)::PEMF(D%NIJT, D%NKT)
REAL, INTENT (IN)::PFRAC_UP(D%NIJT, D%NKT)
TYPE(STACK), INTENT (IN) :: YDSTACK
TYPE(STACK) :: YLSTACK
REAL, INTENT (IN)::PSV_UP(D%NIJT, D%NKT, KSV)
REAL, INTENT (OUT)::PFLXZTKEMF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PFLXZVMF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PFLXZUMF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PFLXZRMF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PFLXZTHVMF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PFLXZTHMF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PFLXZSVMF(D%NIJT, D%NKT, KSV)
temp (REAL, ZVARS, (D%NIJT, D%NKT))
temp (REAL, ZMEMF, (D%NIJT, D%NKT))
INTEGER::JSV
INTEGER::JK
INTEGER::JI
INTEGER::IIJE
INTEGER::IIJB
INTEGER::IKT
temp (REAL, ZRELAX_ALPHA_COEFF, (D%NIJT, D%NKT))


YLSTACK = YDSTACK



IF (KIND (ZVARS) == 8) THEN
    alloc8 (ZVARS)
ELSEIF (KIND (ZVARS) == 4) THEN
    alloc4 (ZVARS)
ELSE
    STOP 1
ENDIF


IF (KIND (ZMEMF) == 8) THEN
    alloc8 (ZMEMF)
ELSEIF (KIND (ZMEMF) == 4) THEN
    alloc4 (ZMEMF)
ELSE
    STOP 1
ENDIF


IF (KIND (ZRELAX_ALPHA_COEFF) == 8) THEN
    alloc8 (ZRELAX_ALPHA_COEFF)
ELSEIF (KIND (ZRELAX_ALPHA_COEFF) == 4) THEN
    alloc4 (ZRELAX_ALPHA_COEFF)
ELSE
    STOP 1
ENDIF


JI = D%NIB


IIJE=D%NIJE
IIJB=D%NIJB
IKT=D%NKT
PFLXZSVMF (JI,:,:)=0.
PSVDT (JI,:,:)=0.

IF (PARAMMF%LRELAX_ALPHA_MF) THEN

  DO JK=1, IKT
    
    ZRELAX_ALPHA_COEFF (JI, JK)=1./(1.-PFRAC_UP (JI, JK))
    ZMEMF (JI, JK)=-PEMF (JI, JK)*ZRELAX_ALPHA_COEFF (JI, JK)
  
  ENDDO

ELSE
  ZRELAX_ALPHA_COEFF (JI, 1:IKT)=1.
  ZMEMF (JI,:)=-PEMF (JI,:)
ENDIF

CALL MZM_MF_OPENACC (D, PTHLM, PFLXZTHMF, YDSTACK=YLSTACK)
CALL MZM_MF_OPENACC (D, PRTM, PFLXZRMF, YDSTACK=YLSTACK)
CALL MZM_MF_OPENACC (D, PTHVM, PFLXZTHVMF, YDSTACK=YLSTACK)

DO JK=1, IKT
  
  PFLXZTHMF (JI, JK)=PEMF (JI, JK)*ZRELAX_ALPHA_COEFF (JI, JK)*(PTHL_UP (JI, JK)-PFLXZTHMF (JI, JK))
  PFLXZRMF (JI, JK)=PEMF (JI, JK)*ZRELAX_ALPHA_COEFF (JI, JK)*(PRT_UP (JI, JK)-PFLXZRMF (JI, JK))
  PFLXZTHVMF (JI, JK)=PEMF (JI, JK)*ZRELAX_ALPHA_COEFF (JI, JK)*(PTHV_UP (JI, JK)-PFLXZTHVMF (JI, JK))
  
ENDDO


IF (PARAMMF%LMIXUV) THEN
  CALL MZM_MF_OPENACC (D, PUM, PFLXZUMF, YDSTACK=YLSTACK)
  CALL MZM_MF_OPENACC (D, PVM, PFLXZVMF, YDSTACK=YLSTACK)

  DO JK=1, IKT
    
    PFLXZUMF (JI, JK)=PEMF (JI, JK)*ZRELAX_ALPHA_COEFF (JI, JK)*(PU_UP (JI, JK)-PFLXZUMF (JI, JK))
    PFLXZVMF (JI, JK)=PEMF (JI, JK)*ZRELAX_ALPHA_COEFF (JI, JK)*(PV_UP (JI, JK)-PFLXZVMF (JI, JK))
  
  ENDDO

ELSE
  PFLXZUMF (JI,:)=0.
  PFLXZVMF (JI,:)=0.
ENDIF


IF (PARAMMF%LMIXTKE) THEN
  CALL MZM_MF_OPENACC (D, PTKEM, PFLXZTKEMF, YDSTACK=YLSTACK)

  DO JK=1, IKT
    
    PFLXZTKEMF (JI, JK)=PEMF (JI, JK)*ZRELAX_ALPHA_COEFF (JI, JK)*(PTKE_UP (JI, JK)-PFLXZTKEMF (JI, JK))
  
  ENDDO

ELSE
  PFLXZTKEMF (JI,:)=0.
ENDIF

CALL TRIDIAG_MASSFLUX_OPENACC (D, PTHLM, PFLXZTHMF, ZMEMF, PTSTEP&
&, PARAMMF%XIMPL_MF, PDZZ, PRHODJ, ZVARS, YDSTACK=YLSTACK)
CALL MZM_MF_OPENACC (D, ZVARS, PFLXZTHMF, YDSTACK=YLSTACK)

DO JK=1, IKT
  
  PFLXZTHMF (JI, JK)=PEMF (JI, JK)*ZRELAX_ALPHA_COEFF (JI, JK)*(PTHL_UP (JI, JK)-PFLXZTHMF (JI, JK))
  PTHLDT (JI, JK)=(ZVARS (JI, JK)-PTHLM (JI, JK))/PTSTEP
  
ENDDO

CALL TRIDIAG_MASSFLUX_OPENACC (D, PRTM, PFLXZRMF, ZMEMF, PTSTEP&
&, PARAMMF%XIMPL_MF, PDZZ, PRHODJ, ZVARS, YDSTACK=YLSTACK)
CALL MZM_MF_OPENACC (D, ZVARS, PFLXZRMF, YDSTACK=YLSTACK)

DO JK=1, IKT
  
  PFLXZRMF (JI, JK)=PEMF (JI, JK)*ZRELAX_ALPHA_COEFF (JI, JK)*(PRT_UP (JI, JK)-PFLXZRMF (JI, JK))
  PRTDT (JI, JK)=(ZVARS (JI, JK)-PRTM (JI, JK))/PTSTEP
  
ENDDO


IF (PARAMMF%LMIXUV) THEN
  CALL TRIDIAG_MASSFLUX_OPENACC (D, PUM, PFLXZUMF, ZMEMF, PTSTEP&
  &, PARAMMF%XIMPL_MF, PDZZ, PRHODJ, ZVARS, YDSTACK=YLSTACK)
  CALL MZM_MF_OPENACC (D, ZVARS, PFLXZUMF, YDSTACK=YLSTACK)

  DO JK=1, IKT
    
    PFLXZUMF (JI, JK)=PEMF (JI, JK)*ZRELAX_ALPHA_COEFF (JI, JK)*(PU_UP (JI, JK)-PFLXZUMF (JI, JK))
    PUDT (JI, JK)=(ZVARS (JI, JK)-PUM (JI, JK))/PTSTEP
  
  ENDDO

  CALL TRIDIAG_MASSFLUX_OPENACC (D, PVM, PFLXZVMF, ZMEMF, PTSTEP&
  &, PARAMMF%XIMPL_MF, PDZZ, PRHODJ, ZVARS, YDSTACK=YLSTACK)
  CALL MZM_MF_OPENACC (D, ZVARS, PFLXZVMF, YDSTACK=YLSTACK)

  DO JK=1, IKT
    
    PFLXZVMF (JI, JK)=PEMF (JI, JK)*ZRELAX_ALPHA_COEFF (JI, JK)*(PV_UP (JI, JK)-PFLXZVMF (JI, JK))
    PVDT (JI, JK)=(ZVARS (JI, JK)-PVM (JI, JK))/PTSTEP
  
  ENDDO

ELSE
  PUDT (JI,:)=0.
  PVDT (JI,:)=0.
ENDIF


DO JSV=1, KSV

  IF (ONOMIXLG.AND.JSV>=KSV_LGBEG.AND.JSV<=KSV_LGEND)  THEN
    CYCLE
  ENDIF

  CALL MZM_MF_OPENACC (D, PSVM (:,:, JSV), PFLXZSVMF (:,:, JSV), YDSTACK=YLSTACK)

  DO JK=1, IKT
    
    PFLXZSVMF (JI, JK, JSV)=PEMF (JI, JK)*ZRELAX_ALPHA_COEFF (JI&
    &, JK)*(PSV_UP (JI, JK, JSV)-PFLXZSVMF (JI, JK, JSV))
  
  ENDDO

  CALL TRIDIAG_MASSFLUX_OPENACC (D, PSVM (:,:, JSV), PFLXZSVMF (:,:, JSV), ZMEMF&
  &, PTSTEP, PARAMMF%XIMPL_MF, PDZZ, PRHODJ, ZVARS, YDSTACK=YLSTACK)
  CALL MZM_MF_OPENACC (D, ZVARS, PFLXZSVMF (:,:, JSV), YDSTACK=YLSTACK)

  DO JK=1, IKT
    
    PFLXZSVMF (JI, JK, JSV)=PEMF (JI, JK)*ZRELAX_ALPHA_COEFF (JI&
    &, JK)*(PSV_UP (JI, JK, JSV)-PFLXZSVMF (JI, JK, JSV))
    PSVDT (JI, JK, JSV)=(ZVARS (JI, JK)-PSVM (JI, JK, JSV))/PTSTEP
  
  ENDDO

ENDDO


IF (PARAMMF%LMIXTKE) THEN
  CALL TRIDIAG_MASSFLUX_OPENACC (D, PTKEM, PFLXZTKEMF, ZMEMF, PTSTEP&
  &, PARAMMF%XIMPL_MF, PDZZ, PRHODJ, ZVARS, YDSTACK=YLSTACK)
  CALL MZM_MF_OPENACC (D, ZVARS, PFLXZTKEMF, YDSTACK=YLSTACK)
  PFLXZTKEMF (JI, 1:IKT)=PEMF (JI, 1:IKT)*ZRELAX_ALPHA_COEFF &
  &(JI, 1:IKT)*(PTKE_UP (JI, 1:IKT)-PFLXZTKEMF (JI, 1:IKT))
  PTKEDT (JI, 1:IKT)=(ZVARS (JI, 1:IKT)-PTKEM (JI, 1:IKT))/PTSTEP
ELSE
  PTKEDT (JI,:)=0.
ENDIF


ENDSUBROUTINE MF_TURB_OPENACC

ENDMODULE MODE_MF_TURB_OPENACC
