INTERFACE

SUBROUTINE SHALLOW_MF(D, CST, NEBN, PARAMMF, TURBN, CSTURB, ICEP, &
KRR, KRRL, KRRI, KSV,                                 &
ONOMIXLG,KSV_LGBEG,KSV_LGEND,                         &
PTSTEP,                                               &
PDZZ, PZZ,                                            &
PRHODJ, PRHODREF,                                     &
PPABSM, PEXNM,                                        &
PSFTH,PSFRV,                                          &
PTHM,PRM,PUM,PVM,PTKEM,PSVM,                          &
PDUDT_MF,PDVDT_MF,PDTKEDT_MF,                         &
PDTHLDT_MF,PDRTDT_MF,PDSVDT_MF,                       &
PSIGMF,PRC_MF,PRI_MF,PCF_MF,                          &
PHLC_HRC, PHLC_HCF, PHLI_HRI, PHLI_HCF,               &
PWEIGHT_MF_CLOUD, PFLXZTHVMF,                         &
PFLXZTHMF,PFLXZRMF,PFLXZUMF,PFLXZVMF,PFLXZTKEMF,      &
PTHL_UP,PRT_UP,PRV_UP,PRC_UP,PRI_UP,                  &
PU_UP, PV_UP, PTKE_UP, PTHV_UP, PW_UP,                &
PFRAC_UP,PEMF,PDETR,PENTR,                            &
KKLCL,KKETL,KKCTL,PDX,PDY,PRSVS,PSVMIN,               &
KBUDGETS                            )
USE MODD_DIMPHYEX,        ONLY: DIMPHYEX_T
USE MODD_CST,             ONLY: CST_T
USE MODD_NEB_N,           ONLY: NEB_T
USE MODD_PARAM_MFSHALL_N, ONLY: PARAM_MFSHALL_T
USE MODD_TURB_N,          ONLY: TURB_T
USE MODD_CTURB,           ONLY: CSTURB_T
USE MODD_RAIN_ICE_PARAM_N, ONLY: RAIN_ICE_PARAM_T
USE MODD_PARAMETERS,      ONLY: JPSVMAX
IMPLICIT NONE
TYPE(DIMPHYEX_T),       INTENT(IN)   :: D
TYPE(CST_T),            INTENT(IN)   :: CST
TYPE(NEB_T),            INTENT(IN)   :: NEBN
TYPE(PARAM_MFSHALL_T),  INTENT(IN)   :: PARAMMF
TYPE(TURB_T),           INTENT(IN)   :: TURBN
TYPE(CSTURB_T),         INTENT(IN)   :: CSTURB
TYPE(RAIN_ICE_PARAM_T), INTENT(IN)   :: ICEP
INTEGER,                INTENT(IN)   :: KRR
INTEGER,                INTENT(IN)   :: KRRL
INTEGER,                INTENT(IN)   :: KRRI
INTEGER,                INTENT(IN)   :: KSV
LOGICAL,                INTENT(IN)   :: ONOMIXLG
INTEGER,                INTENT(IN)   :: KSV_LGBEG
INTEGER,                INTENT(IN)   :: KSV_LGEND
REAL,                   INTENT(IN)   :: PTSTEP
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN) ::  PZZ
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN) ::  PDZZ
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN) ::  PRHODJ
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN) ::  PRHODREF
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN) ::  PPABSM
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN) ::  PEXNM
REAL, DIMENSION(D%NIJT),         INTENT(IN) ::  PSFTH,PSFRV
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN) ::  PTHM
REAL, DIMENSION(D%NIJT,D%NKT,KRR), INTENT(IN) ::  PRM
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN) ::  PUM,PVM
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN) ::  PTKEM
REAL, DIMENSION(D%NIJT,D%NKT,KSV), INTENT(IN) ::  PSVM
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(OUT)::  PDUDT_MF
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(OUT)::  PDVDT_MF
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(OUT)::  PDTKEDT_MF
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(OUT)::  PDTHLDT_MF
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(OUT)::  PDRTDT_MF
REAL, DIMENSION(D%NIJT,D%NKT,KSV), INTENT(OUT)::  PDSVDT_MF
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT)     ::  PSIGMF,PRC_MF,PRI_MF,PCF_MF
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT)     ::  PHLC_HRC, PHLC_HCF, PHLI_HRI, PHLI_HCF
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT)     ::  PWEIGHT_MF_CLOUD
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT)     ::  PFLXZTHVMF
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT)     ::  PFLXZTHMF
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT)     ::  PFLXZRMF
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT)     ::  PFLXZUMF
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT)     ::  PFLXZVMF
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT)     ::  PFLXZTKEMF
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) ::  PTHL_UP
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) ::  PRT_UP
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) ::  PRV_UP
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) ::  PU_UP
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) ::  PV_UP
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) ::  PTKE_UP
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) ::  PRC_UP
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) ::  PRI_UP
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) ::  PTHV_UP
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) ::  PW_UP
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) ::  PFRAC_UP
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) ::  PEMF
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT) ::  PDETR
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT) ::  PENTR
INTEGER,DIMENSION(D%NIJT),     INTENT(OUT) :: KKLCL,KKETL,KKCTL
REAL,                          INTENT(IN)  :: PDX, PDY
REAL, DIMENSION(D%NIJT,D%NKT,KSV),      INTENT(IN),    OPTIONAL :: PRSVS
REAL,DIMENSION(JPSVMAX),                INTENT(IN),    OPTIONAL :: PSVMIN
INTEGER,                                INTENT(IN)              :: KBUDGETS
END SUBROUTINE SHALLOW_MF


SUBROUTINE SHALLOW_MF_OPENACC (D, CST, NEBN, PARAMMF, TURBN, CSTURB, ICEP, KRR, KRRL, KRRI, KSV&
&, ONOMIXLG, KSV_LGBEG, KSV_LGEND, PTSTEP, PDZZ, PZZ, PRHODJ, PRHODREF, PPABSM, PEXNM, PSFTH,&
& PSFRV, PTHM, PRM, PUM, PVM, PTKEM, PSVM, PDUDT_MF, PDVDT_MF, PDTKEDT_MF, PDTHLDT_MF, PDRTDT_MF&
&, PDSVDT_MF, PSIGMF, PRC_MF, PRI_MF, PCF_MF, PHLC_HRC, PHLC_HCF, PHLI_HRI, PHLI_HCF, PWEIGHT_MF_CLOUD&
&, PFLXZTHVMF, PFLXZTHMF, PFLXZRMF, PFLXZUMF, PFLXZVMF, PFLXZTKEMF, PTHL_UP, PRT_UP, PRV_UP, PRC_UP&
&, PRI_UP, PU_UP, PV_UP, PTKE_UP, PTHV_UP, PW_UP, PFRAC_UP, PEMF, PDETR, PENTR, KKLCL, KKETL,&
& KKCTL, PDX, PDY, PRSVS, PSVMIN, KBUDGETS, YDSTACK)
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODD_CST,ONLY:CST_T
USE MODD_NEB_N,ONLY:NEB_T
USE MODD_PARAM_MFSHALL_N,ONLY:PARAM_MFSHALL_T
USE MODD_TURB_N,ONLY:TURB_T
USE MODD_CTURB,ONLY:CSTURB_T
USE MODD_RAIN_ICE_PARAM_N,ONLY:RAIN_ICE_PARAM_T
USE MODD_PARAMETERS,ONLY:JPSVMAX
USE STACK_MOD
USE ABOR1_ACC_MOD
IMPLICIT NONE
!$ACC ROUTINE (SHALLOW_MF_OPENACC) SEQ
TYPE (DIMPHYEX_T), INTENT (IN)::D
TYPE (CST_T), INTENT (IN)::CST
TYPE (NEB_T), INTENT (IN)::NEBN
TYPE (PARAM_MFSHALL_T), INTENT (IN)::PARAMMF
TYPE (TURB_T), INTENT (IN)::TURBN
TYPE (CSTURB_T), INTENT (IN)::CSTURB
TYPE (RAIN_ICE_PARAM_T), INTENT (IN)::ICEP
INTEGER, INTENT (IN)::KRR
INTEGER, INTENT (IN)::KRRL
INTEGER, INTENT (IN)::KRRI
INTEGER, INTENT (IN)::KSV
LOGICAL, INTENT (IN)::ONOMIXLG
INTEGER, INTENT (IN)::KSV_LGBEG
INTEGER, INTENT (IN)::KSV_LGEND
REAL, INTENT (IN)::PTSTEP
REAL, INTENT (IN)::PZZ(D%NIJT, D%NKT)
REAL, INTENT (IN)::PDZZ(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRHODJ(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRHODREF(D%NIJT, D%NKT)
REAL, INTENT (IN)::PPABSM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PEXNM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PSFRV(D%NIJT)
REAL, INTENT (IN)::PSFTH(D%NIJT)
REAL, INTENT (IN)::PTHM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRM(D%NIJT, D%NKT, KRR)
REAL, INTENT (IN)::PVM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PUM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PTKEM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PSVM(D%NIJT, D%NKT, KSV)
REAL, INTENT (OUT)::PDUDT_MF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PDVDT_MF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PDTKEDT_MF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PDTHLDT_MF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PDRTDT_MF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PDSVDT_MF(D%NIJT, D%NKT, KSV)
REAL, INTENT (OUT)::PCF_MF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PRI_MF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PRC_MF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PSIGMF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PHLI_HCF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PHLI_HRI(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PHLC_HCF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PHLC_HRC(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PWEIGHT_MF_CLOUD(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PFLXZTHVMF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PFLXZTHMF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PFLXZRMF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PFLXZUMF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PFLXZVMF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PFLXZTKEMF(D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PTHL_UP(D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PRT_UP(D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PRV_UP(D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PU_UP(D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PV_UP(D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PTKE_UP(D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PRC_UP(D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PRI_UP(D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PTHV_UP(D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PW_UP(D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PFRAC_UP(D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PEMF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PDETR(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PENTR(D%NIJT, D%NKT)
INTEGER, INTENT (OUT)::KKCTL(D%NIJT)
INTEGER, INTENT (OUT)::KKETL(D%NIJT)
INTEGER, INTENT (OUT)::KKLCL(D%NIJT)
REAL, INTENT (IN)::PDY
REAL, INTENT (IN)::PDX
REAL, INTENT (IN), OPTIONAL::PRSVS(D%NIJT, D%NKT, KSV)
REAL, INTENT (IN), OPTIONAL::PSVMIN(JPSVMAX)
INTEGER, INTENT (IN)::KBUDGETS
TYPE(STACK), INTENT (IN) :: YDSTACK

ENDSUBROUTINE SHALLOW_MF_OPENACC

SUBROUTINE SHALLOW_MF_BITREPRO(D, CST, NEBN, PARAMMF, TURBN, CSTURB, ICEP, &
KRR, KRRL, KRRI, KSV,                                 &
ONOMIXLG,KSV_LGBEG,KSV_LGEND,                         &
PTSTEP,                                               &
PDZZ, PZZ,                                            &
PRHODJ, PRHODREF,                                     &
PPABSM, PEXNM,                                        &
PSFTH,PSFRV,                                          &
PTHM,PRM,PUM,PVM,PTKEM,PSVM,                          &
PDUDT_MF,PDVDT_MF,PDTKEDT_MF,                         &
PDTHLDT_MF,PDRTDT_MF,PDSVDT_MF,                       &
PSIGMF,PRC_MF,PRI_MF,PCF_MF,                          &
PHLC_HRC, PHLC_HCF, PHLI_HRI, PHLI_HCF,               &
PWEIGHT_MF_CLOUD, PFLXZTHVMF,                         &
PFLXZTHMF,PFLXZRMF,PFLXZUMF,PFLXZVMF,PFLXZTKEMF,      &
PTHL_UP,PRT_UP,PRV_UP,PRC_UP,PRI_UP,                  &
PU_UP, PV_UP, PTKE_UP, PTHV_UP, PW_UP,                &
PFRAC_UP,PEMF,PDETR,PENTR,                            &
KKLCL,KKETL,KKCTL,PDX,PDY,PRSVS,PSVMIN,               &
KBUDGETS                            )
USE MODD_DIMPHYEX,        ONLY: DIMPHYEX_T
USE MODD_CST,             ONLY: CST_T
USE MODD_NEB_N,           ONLY: NEB_T
USE MODD_PARAM_MFSHALL_N, ONLY: PARAM_MFSHALL_T
USE MODD_TURB_N,          ONLY: TURB_T
USE MODD_CTURB,           ONLY: CSTURB_T
USE MODD_RAIN_ICE_PARAM_N, ONLY: RAIN_ICE_PARAM_T
USE MODD_PARAMETERS,      ONLY: JPSVMAX
IMPLICIT NONE
TYPE(DIMPHYEX_T),       INTENT(IN)   :: D
TYPE(CST_T),            INTENT(IN)   :: CST
TYPE(NEB_T),            INTENT(IN)   :: NEBN
TYPE(PARAM_MFSHALL_T),  INTENT(IN)   :: PARAMMF
TYPE(TURB_T),           INTENT(IN)   :: TURBN
TYPE(CSTURB_T),         INTENT(IN)   :: CSTURB
TYPE(RAIN_ICE_PARAM_T), INTENT(IN)   :: ICEP
INTEGER,                INTENT(IN)   :: KRR
INTEGER,                INTENT(IN)   :: KRRL
INTEGER,                INTENT(IN)   :: KRRI
INTEGER,                INTENT(IN)   :: KSV
LOGICAL,                INTENT(IN)   :: ONOMIXLG
INTEGER,                INTENT(IN)   :: KSV_LGBEG
INTEGER,                INTENT(IN)   :: KSV_LGEND
REAL,                   INTENT(IN)   :: PTSTEP
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN) ::  PZZ
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN) ::  PDZZ
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN) ::  PRHODJ
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN) ::  PRHODREF
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN) ::  PPABSM
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN) ::  PEXNM
REAL, DIMENSION(D%NIJT),         INTENT(IN) ::  PSFTH,PSFRV
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN) ::  PTHM
REAL, DIMENSION(D%NIJT,D%NKT,KRR), INTENT(IN) ::  PRM
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN) ::  PUM,PVM
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN) ::  PTKEM
REAL, DIMENSION(D%NIJT,D%NKT,KSV), INTENT(IN) ::  PSVM
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(OUT)::  PDUDT_MF
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(OUT)::  PDVDT_MF
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(OUT)::  PDTKEDT_MF
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(OUT)::  PDTHLDT_MF
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(OUT)::  PDRTDT_MF
REAL, DIMENSION(D%NIJT,D%NKT,KSV), INTENT(OUT)::  PDSVDT_MF
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT)     ::  PSIGMF,PRC_MF,PRI_MF,PCF_MF
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT)     ::  PHLC_HRC, PHLC_HCF, PHLI_HRI, PHLI_HCF
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT)     ::  PWEIGHT_MF_CLOUD
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT)     ::  PFLXZTHVMF
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT)     ::  PFLXZTHMF
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT)     ::  PFLXZRMF
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT)     ::  PFLXZUMF
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT)     ::  PFLXZVMF
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT)     ::  PFLXZTKEMF
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) ::  PTHL_UP
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) ::  PRT_UP
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) ::  PRV_UP
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) ::  PU_UP
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) ::  PV_UP
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) ::  PTKE_UP
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) ::  PRC_UP
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) ::  PRI_UP
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) ::  PTHV_UP
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) ::  PW_UP
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) ::  PFRAC_UP
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) ::  PEMF
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT) ::  PDETR
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT) ::  PENTR
INTEGER,DIMENSION(D%NIJT),     INTENT(OUT) :: KKLCL,KKETL,KKCTL
REAL,                          INTENT(IN)  :: PDX, PDY
REAL, DIMENSION(D%NIJT,D%NKT,KSV),      INTENT(IN),    OPTIONAL :: PRSVS
REAL,DIMENSION(JPSVMAX),                INTENT(IN),    OPTIONAL :: PSVMIN
INTEGER,                                INTENT(IN)              :: KBUDGETS
END SUBROUTINE SHALLOW_MF_BITREPRO


END INTERFACE
