
MODULE MODE_COMPUTE_MF_CLOUD_BIGAUS_OPENACC


IMPLICIT NONE


CONTAINS
SUBROUTINE COMPUTE_MF_CLOUD_BIGAUS_OPENACC (D, CST, PARAMMF, ICEP, KRR, PRT_UP, PRV_UP, PRC_UP&
&, PRI_UP, PTH_UP, PFRAC_UP, PRTM, PTHM, PRM, PRHODREF, PEXNM, PPABSM, PRC_MF, PRI_MF, PCF_MF&
&, PSIGMF, PHLC_HRC, PHLC_HCF, PHLI_HRI, PHLI_HCF, PWEIGHT_MF_CLOUD, YDSTACK)
!$ACC ROUTINE (COMPUTE_MF_CLOUD_BIGAUS_OPENACC) SEQ
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODD_CST,ONLY:CST_T
USE MODD_PARAM_MFSHALL_N,ONLY:PARAM_MFSHALL_T
USE MODD_RAIN_ICE_PARAM_N,ONLY:RAIN_ICE_PARAM_T
USE MODE_SHUMAN_MF_OPENACC,ONLY:MZF_MF_OPENACC

#include "stack.h"
USE STACK_MOD
USE ABOR1_ACC_MOD

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
TYPE (CST_T), INTENT (IN)::CST
TYPE (PARAM_MFSHALL_T), INTENT (IN)::PARAMMF
TYPE (RAIN_ICE_PARAM_T), INTENT (IN)::ICEP
INTEGER, INTENT (IN)::KRR
REAL, INTENT (IN)::PFRAC_UP(D%NIJT, D%NKT)
REAL, INTENT (IN)::PTH_UP(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRI_UP(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRC_UP(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRV_UP(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRT_UP(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRTM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PTHM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRM(D%NIJT, D%NKT, KRR)
REAL, INTENT (IN)::PPABSM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PEXNM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRHODREF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PRI_MF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PRC_MF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PCF_MF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PSIGMF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PHLI_HRI(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PHLI_HCF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PHLC_HRC(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PHLC_HCF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PWEIGHT_MF_CLOUD(D%NIJT, D%NKT)
TYPE(STACK), INTENT (IN) :: YDSTACK
TYPE(STACK) :: YLSTACK
INTEGER::JI
INTEGER::JK
INTEGER::IKT
INTEGER::IIJB
INTEGER::IIJE
temp (REAL, ZFRAC_UP_M, (D%NIJT, D%NKT))
temp (REAL, ZTH_UP_M, (D%NIJT, D%NKT))
temp (REAL, ZRI_UP_M, (D%NIJT, D%NKT))
temp (REAL, ZRC_UP_M, (D%NIJT, D%NKT))
temp (REAL, ZRV_UP_M, (D%NIJT, D%NKT))
temp (REAL, ZRT_UP_M, (D%NIJT, D%NKT))
REAL::ZSBAR_UP
REAL::ZFRAC_ICE
REAL::ZFRAC_ICE_UP_M
REAL::ZGAM
REAL::ZCOND
REAL::ZAUT
REAL::ZCRIAUTI
REAL::ZGAUI
REAL::ZGAUTI
REAL::ZAUTI
REAL::ZGAUC
REAL::ZGAUTC
REAL::ZAUTC
REAL::ZQSI
REAL::ZPV
REAL::ZSIGS_UP
REAL::ZSBAR_ENV
REAL::ZSBAR_MEAN
REAL::ZA
REAL::ZAH
REAL::ZQSL
REAL::ZLVS
REAL::ZLS
REAL::ZLV
REAL::ZTEMP_UP
REAL::ZTEMP
REAL::ZCPH
REAL::ZQ1


YLSTACK = YDSTACK



IF (KIND (ZFRAC_UP_M) == 8) THEN
    alloc8 (ZFRAC_UP_M)
ELSEIF (KIND (ZFRAC_UP_M) == 4) THEN
    alloc4 (ZFRAC_UP_M)
ELSE
    STOP 1
ENDIF


IF (KIND (ZTH_UP_M) == 8) THEN
    alloc8 (ZTH_UP_M)
ELSEIF (KIND (ZTH_UP_M) == 4) THEN
    alloc4 (ZTH_UP_M)
ELSE
    STOP 1
ENDIF


IF (KIND (ZRI_UP_M) == 8) THEN
    alloc8 (ZRI_UP_M)
ELSEIF (KIND (ZRI_UP_M) == 4) THEN
    alloc4 (ZRI_UP_M)
ELSE
    STOP 1
ENDIF


IF (KIND (ZRC_UP_M) == 8) THEN
    alloc8 (ZRC_UP_M)
ELSEIF (KIND (ZRC_UP_M) == 4) THEN
    alloc4 (ZRC_UP_M)
ELSE
    STOP 1
ENDIF


IF (KIND (ZRV_UP_M) == 8) THEN
    alloc8 (ZRV_UP_M)
ELSEIF (KIND (ZRV_UP_M) == 4) THEN
    alloc4 (ZRV_UP_M)
ELSE
    STOP 1
ENDIF


IF (KIND (ZRT_UP_M) == 8) THEN
    alloc8 (ZRT_UP_M)
ELSEIF (KIND (ZRT_UP_M) == 4) THEN
    alloc4 (ZRT_UP_M)
ELSE
    STOP 1
ENDIF


JI = D%NIB


IIJE=D%NIJE
IIJB=D%NIJB
IKT=D%NKT
CALL MZF_MF_OPENACC (D, PRC_UP, ZRC_UP_M, YDSTACK=YLSTACK)
CALL MZF_MF_OPENACC (D, PRI_UP, ZRI_UP_M, YDSTACK=YLSTACK)
CALL MZF_MF_OPENACC (D, PRT_UP, ZRT_UP_M, YDSTACK=YLSTACK)
CALL MZF_MF_OPENACC (D, PRV_UP, ZRV_UP_M, YDSTACK=YLSTACK)
CALL MZF_MF_OPENACC (D, PFRAC_UP, ZFRAC_UP_M, YDSTACK=YLSTACK)
CALL MZF_MF_OPENACC (D, PTH_UP, ZTH_UP_M, YDSTACK=YLSTACK)
PWEIGHT_MF_CLOUD (JI,:)=0.

DO JK=1, IKT

  

  IF (ZFRAC_UP_M (JI, JK)>0.) THEN
    ZFRAC_ICE_UP_M=0.

    IF (ZRC_UP_M (JI, JK)+ZRI_UP_M (JI, JK)>1.E-20) THEN
      ZFRAC_ICE_UP_M=ZRI_UP_M (JI, JK)/(ZRC_UP_M (JI, JK)+ZRI_UP_M (JI, JK))
    ENDIF

    ZFRAC_ICE=0.

    IF (KRR>3) THEN

      IF (PRM (JI, JK, 2)+PRM (JI, JK, 4)>1.E-20) THEN
        ZFRAC_ICE=PRM (JI, JK, 4)/(PRM (JI, JK, 2)+PRM (JI, JK, 4))
      ENDIF

    ENDIF

    ZCPH=CST%XCPD+CST%XCPV*ZRV_UP_M (JI, JK)+CST%XCL*ZRC_UP_M (JI, JK)+CST%XCI*ZRI_UP_M (JI, JK)
    ZTEMP_UP=ZTH_UP_M (JI, JK)*PEXNM (JI, JK)
    ZLV=CST%XLVTT+(CST%XCPV-CST%XCL)*(ZTEMP_UP-CST%XTT)
    ZLS=CST%XLSTT+(CST%XCPV-CST%XCI)*(ZTEMP_UP-CST%XTT)
    ZPV=MIN (EXP (CST%XALPW-CST%XBETAW/ZTEMP_UP-CST%XGAMW*LOG (ZTEMP_UP)),.99*PPABSM (JI, JK))
    ZQSL=CST%XRD/CST%XRV*ZPV/(PPABSM (JI, JK)-ZPV)
    ZPV=MIN (EXP (CST%XALPI-CST%XBETAI/ZTEMP_UP-CST%XGAMI*LOG (ZTEMP_UP)),.99*PPABSM (JI, JK))
    ZQSI=CST%XRD/CST%XRV*ZPV/(PPABSM (JI, JK)-ZPV)
    ZQSL=(1.-ZFRAC_ICE_UP_M)*ZQSL+ZFRAC_ICE_UP_M*ZQSI
    ZLVS=(1.-ZFRAC_ICE_UP_M)*ZLV+ZFRAC_ICE_UP_M*ZLS
    ZAH=ZLVS*ZQSL/(CST%XRV*ZTEMP_UP**2)*(1.+(CST%XRV*ZQSL/CST%XRD))
    ZA=1./(1.+ZLVS/ZCPH*ZAH)
    ZSBAR_UP=ZA*(ZRT_UP_M (JI, JK)-ZQSL+ZAH*ZLVS*(ZRC_UP_M (JI, JK)+ZRI_UP_M (JI, JK))/ZCPH)

    IF (KRR>3) THEN
      ZCPH=CST%XCPD+CST%XCPV*PRM (JI, JK, 1)+CST%XCL*PRM (JI, JK, 2)+CST%XCI*PRM (JI, JK, 4)
    ELSE
      ZCPH=CST%XCPD+CST%XCPV*PRM (JI, JK, 1)+CST%XCL*PRM (JI, JK, 2)
    ENDIF

    ZTEMP=PTHM (JI, JK)*PEXNM (JI, JK)
    ZLV=CST%XLVTT+(CST%XCPV-CST%XCL)*(ZTEMP-CST%XTT)
    ZLS=CST%XLSTT+(CST%XCPV-CST%XCI)*(ZTEMP-CST%XTT)
    ZPV=MIN (EXP (CST%XALPW-CST%XBETAW/ZTEMP-CST%XGAMW*LOG (ZTEMP)),.99*PPABSM (JI, JK))
    ZQSL=CST%XRD/CST%XRV*ZPV/(PPABSM (JI, JK)-ZPV)
    ZPV=MIN (EXP (CST%XALPI-CST%XBETAI/ZTEMP-CST%XGAMI*LOG (ZTEMP)),.99*PPABSM (JI, JK))
    ZQSI=CST%XRD/CST%XRV*ZPV/(PPABSM (JI, JK)-ZPV)
    ZQSL=(1.-ZFRAC_ICE)*ZQSL+ZFRAC_ICE*ZQSI
    ZLVS=(1.-ZFRAC_ICE)*ZLV+ZFRAC_ICE*ZLS
    ZAH=ZLVS*ZQSL/(CST%XRV*ZTEMP**2)*(1.+(CST%XRV*ZQSL/CST%XRD))
    ZA=1./(1.+ZLVS/ZCPH*ZAH)

    IF (KRR>3) THEN
      ZSBAR_MEAN=ZA*(PRTM (JI, JK)-ZQSL+ZAH*ZLVS*(PRM (JI, JK, 2)+PRM (JI, JK, 4))/ZCPH)
    ELSE
      ZSBAR_MEAN=ZA*(PRTM (JI, JK)-ZQSL+ZAH*ZLVS*PRM (JI, JK, 2)/ZCPH)
    ENDIF

    ZSBAR_ENV=(ZSBAR_MEAN-ZFRAC_UP_M (JI, JK)*ZSBAR_UP)/(1.-ZFRAC_UP_M (JI, JK))
    PSIGMF (JI, JK)=PARAMMF%XSIGMA_ENV*(1.-ZFRAC_UP_M (JI, JK))*(ZSBAR_ENV-ZSBAR_MEAN)**2
    ZSIGS_UP=PARAMMF%XSIGMA_MF*ZFRAC_UP_M (JI, JK)*(ZSBAR_UP-ZSBAR_MEAN)**2
    ZSIGS_UP=SQRT (MAX (ABS (ZSIGS_UP), 1.E-40))
    PWEIGHT_MF_CLOUD (JI, JK)=ZFRAC_UP_M (JI, JK)*PARAMMF%XALPHA_MF
    PWEIGHT_MF_CLOUD (JI, JK)=MAX (0., MIN (PWEIGHT_MF_CLOUD (JI, JK), 1.))
    ZQ1=ZSBAR_UP/ZSIGS_UP
    ZA=-ZQ1/SQRT (2.)
    ZGAM=1+ERF (-ZA)
    ZCOND=(EXP (-ZA**2)-ZA*SQRT (CST%XPI)*ZGAM)*ZSIGS_UP/SQRT (2.*CST%XPI)*PWEIGHT_MF_CLOUD (JI, JK)
    PCF_MF (JI, JK)=MAX (0., MIN (1., 0.5*ZGAM*PWEIGHT_MF_CLOUD (JI, JK)))
    ZCOND=MAX (ZCOND, 0.)

    IF (ZCOND<1.E-12.OR.PCF_MF (JI, JK)==0.) THEN
      PCF_MF (JI, JK)=0.
      ZCOND=0.
    ENDIF

    PRC_MF (JI, JK)=(1.-ZFRAC_ICE_UP_M)*ZCOND
    PRI_MF (JI, JK)=ZFRAC_ICE_UP_M*ZCOND

    IF (1-ZFRAC_ICE_UP_M>1.E-20) THEN
      ZAUTC=(ZSBAR_UP-ICEP%XCRIAUTC/(PRHODREF (JI, JK)*(1-ZFRAC_ICE_UP_M)))/ZSIGS_UP
      ZGAUTC=-ZAUTC/SQRT (2.)
      ZGAUC=1+ERF (-ZGAUTC)
      PHLC_HRC (JI, JK)=(1-ZFRAC_ICE_UP_M)*(EXP (-ZGAUTC**2)-ZGAUTC*SQRT (CST&
      &%XPI)*ZGAUC)*ZSIGS_UP/SQRT (2.*CST%XPI)*PWEIGHT_MF_CLOUD (JI, JK)
      PHLC_HCF (JI, JK)=MAX (0., MIN (1., 0.5*ZGAUC))*PWEIGHT_MF_CLOUD (JI, JK)
      PHLC_HRC (JI, JK)=PHLC_HRC (JI, JK)+ICEP%XCRIAUTC/PRHODREF (JI, JK)*PHLC_HCF (JI, JK)
      PHLC_HRC (JI, JK)=MAX (PHLC_HRC (JI, JK), 0.)

      IF (PHLC_HRC (JI, JK)<1.E-12.OR.PHLC_HCF (JI, JK)<1.E-6) THEN
        PHLC_HRC (JI, JK)=0.
        PHLC_HCF (JI, JK)=0.
      ENDIF

    ELSE
      PHLC_HCF (JI, JK)=0.
      PHLC_HRC (JI, JK)=0.
    ENDIF


    IF (ZFRAC_ICE_UP_M>1.E-20) THEN
      ZCRIAUTI=MIN (ICEP%XCRIAUTI, 10**(ICEP%XACRIAUTI*(ZTEMP_UP-CST%XTT)+ICEP%XBCRIAUTI))
      ZAUTI=(ZSBAR_UP-ZCRIAUTI/ZFRAC_ICE_UP_M)/ZSIGS_UP
      ZGAUTI=-ZAUTI/SQRT (2.)
      ZGAUI=1+ERF (-ZGAUTI)
      PHLI_HRI (JI, JK)=ZFRAC_ICE_UP_M*(EXP (-ZGAUTI**2)-ZGAUTI*SQRT (CST%XPI&
      &)*ZGAUI)*ZSIGS_UP/SQRT (2.*CST%XPI)*PWEIGHT_MF_CLOUD (JI, JK)
      PHLI_HCF (JI, JK)=MAX (0., MIN (1., 0.5*ZGAUI))*PWEIGHT_MF_CLOUD (JI, JK)
      PHLI_HRI (JI, JK)=PHLI_HRI (JI, JK)+ZCRIAUTI*PHLI_HCF (JI, JK)
      PHLI_HRI (JI, JK)=MAX (PHLI_HRI (JI, JK), 0.)

      IF (PHLI_HRI (JI, JK)<1.E-12.OR.PHLI_HCF (JI, JK)<1.E-6) THEN
        PHLI_HRI (JI, JK)=0.
        PHLI_HCF (JI, JK)=0.
      ENDIF

    ELSE
      PHLI_HCF (JI, JK)=0.
      PHLI_HRI (JI, JK)=0.
    ENDIF

  ELSE
    PCF_MF (JI, JK)=0.
    PRC_MF (JI, JK)=0.
    PRI_MF (JI, JK)=0.
    PHLC_HCF (JI, JK)=0.
    PHLC_HRC (JI, JK)=0.
    PHLI_HCF (JI, JK)=0.
    PHLI_HRI (JI, JK)=0.
  ENDIF

  
ENDDO


IF (.NOT.PARAMMF%LRELAX_ALPHA_MF) THEN
  PWEIGHT_MF_CLOUD (JI,:)=0.
ENDIF


ENDSUBROUTINE COMPUTE_MF_CLOUD_BIGAUS_OPENACC

ENDMODULE MODE_COMPUTE_MF_CLOUD_BIGAUS_OPENACC
