[
  '--object-merge-method', 'concatenate-include',
  '--stack84',
  '--methods-list', 'save,load,copy,wipe',
  '--merge-interfaces',
  '--parallelmethod-section',
  '--numbered-submodules',
  '--inline-contained',
  '--max-statements-per-parallel','20',
  '--tmp', '1' # '/home/gmap/mrpm/marguina/shallow_mf/compile.cpu_intel_d/t    mp',
]

