PROGRAM MAIN_SHALLOW_MF

#ifdef __NVCOMPILER
USE NVTX
#endif

USE YOMDATA
USE MODE_SHUMAN_PHY, ONLY: MXM_PHY, MYM_PHY
USE YOMHOOK,    ONLY: LHOOK, DR_HOOK, JPHOOK

USE MODD_BUDGET,          ONLY: TBUDGETCONF_t, TBUDGETDATA_PTR, NBUDGET_U,  NBUDGET_V, &
                                NBUDGET_TH,  NBUDGET_RV, NBUDGET_SV1
USE MODD_DIMPHYEX,        ONLY: DIMPHYEX_t
USE MODD_CST,             ONLY: CST_t
USE MODD_NEB_n,           ONLY: NEB_t
USE MODD_PARAM_MFSHALL_n, ONLY: PARAM_MFSHALL_t
USE MODD_TURB_n,          ONLY: TURB_t
USE MODD_CTURB,           ONLY: CSTURB_t
USE MODD_RAIN_ICE_PARAM_n,ONLY: RAIN_ICE_PARAM_t
USE MODD_PARAMETERS,      ONLY: JPSVMAX

USE MODE_COMPUTE_MF_CLOUD,       ONLY: COMPUTE_MF_CLOUD
USE MODE_COMPUTE_UPDRAFT,        ONLY: COMPUTE_UPDRAFT
USE MODE_COMPUTE_UPDRAFT_RAHA,   ONLY: COMPUTE_UPDRAFT_RAHA
USE MODE_COMPUTE_UPDRAFT_RHCJ10, ONLY: COMPUTE_UPDRAFT_RHCJ10
USE MODE_MF_TURB,                ONLY: MF_TURB
USE MODE_MF_TURB_EXPL,           ONLY: MF_TURB_EXPL
USE MODE_MSG,                    ONLY: PRINT_MSG, NVERB_FATAL
USE MODE_THL_RT_FROM_TH_R_MF,    ONLY: THL_RT_FROM_TH_R_MF

USE UTIL_CSTURB_T_MOD
USE UTIL_TURB_T_MOD
USE UTIL_PARAM_MFSHALL_T_MOD
USE UTIL_NEB_T_MOD
USE UTIL_CST_T_MOD
USE UTIL_DIMPHYEX_T_MOD
USE UTIL_RAIN_ICE_PARAM_T_MOD
USE XRD_GETOPTIONS
USE XRD_UNIX_ENV

#include "stack.h"

USE STACK_MOD

USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : STDOUT => OUTPUT_UNIT

IMPLICIT NONE

TYPE(DIMPHYEX_t)       :: D,DD            
TYPE(CST_t)            :: CST          
TYPE(NEB_t)            :: NEBN
TYPE(PARAM_MFSHALL_t)  :: PARAMMF
TYPE(TURB_t)           :: TURBN        
TYPE(CSTURB_t)         :: CSTURB   
TYPE(RAIN_ICE_PARAM_t) :: ICEP    
INTEGER(KIND=JPIM)                :: KRR          
INTEGER(KIND=JPIM)                :: KRRL         
INTEGER(KIND=JPIM)                :: KRRI         
INTEGER(KIND=JPIM)                :: KSV          
LOGICAL(KIND=JPIM)                :: ONOMIXLG  
INTEGER(KIND=JPIM)                :: KSV_LGBEG 
INTEGER(KIND=JPIM)                :: KSV_LGEND 
REAL(KIND=JPRB)                   :: PTSTEP    
REAL(KIND=JPRB), POINTER          :: ZZZ  (:,:,:)       
REAL(KIND=JPRB), POINTER          :: ZDZZ  (:,:,:)      
REAL(KIND=JPRB), POINTER          :: ZRHODJ  (:,:,:)    
REAL(KIND=JPRB), POINTER          :: ZRHODREF  (:,:,:)  
REAL(KIND=JPRB), POINTER          :: ZPABSM  (:,:,:)    
REAL(KIND=JPRB), POINTER          :: ZEXNM  (:,:,:)     

REAL(KIND=JPRB), POINTER          :: ZSFTH (:,:)
REAL(KIND=JPRB), POINTER          :: ZSFRV (:,:)
REAL(KIND=JPRB), POINTER          :: ZTHM  (:,:,:)      
REAL(KIND=JPRB), POINTER          :: ZRM  (:,:,:,:)       
REAL(KIND=JPRB), POINTER          :: ZUM  (:,:,:)    
REAL(KIND=JPRB), POINTER          :: ZVM (:,:,:)
REAL(KIND=JPRB), POINTER          :: ZTKEM  (:,:,:)     
REAL(KIND=JPRB), POINTER          :: ZSVM  (:,:,:,:)      

REAL(KIND=JPRB), POINTER          :: ZDUDT_MF  (:,:,:)   
REAL(KIND=JPRB), POINTER          :: ZDVDT_MF  (:,:,:)
REAL(KIND=JPRB), POINTER          :: ZDTKEDT_MF  (:,:,:)  
REAL(KIND=JPRB), POINTER          :: ZDTHLDT_MF  (:,:,:) 
REAL(KIND=JPRB), POINTER          :: ZDRTDT_MF  (:,:,:)  
REAL(KIND=JPRB), POINTER          :: ZDSVDT_MF (:,:,:,:)

REAL(KIND=JPRB), POINTER          :: ZSIGMF (:,:,:)
REAL(KIND=JPRB), POINTER          :: ZRC_MF (:,:,:)
REAL(KIND=JPRB), POINTER          :: ZRI_MF (:,:,:)
REAL(KIND=JPRB), POINTER          :: ZCF_MF (:,:,:)
REAL(KIND=JPRB), POINTER          :: ZHLC_HRC (:,:,:)
REAL(KIND=JPRB), POINTER          :: ZHLC_HCF (:,:,:)
REAL(KIND=JPRB), POINTER          :: ZHLI_HRI (:,:,:)
REAL(KIND=JPRB), POINTER          :: ZHLI_HCF (:,:,:)
REAL(KIND=JPRB), POINTER          :: ZWEIGHT_MF_CLOUD (:,:,:)
REAL(KIND=JPRB), POINTER          :: ZFLXZTHVMF (:,:,:)          
REAL(KIND=JPRB), POINTER          :: ZFLXZTHMF (:,:,:) 
REAL(KIND=JPRB), POINTER          :: ZFLXZRMF  (:,:,:)
REAL(KIND=JPRB), POINTER          :: ZFLXZUMF  (:,:,:)
REAL(KIND=JPRB), POINTER          :: ZFLXZVMF  (:,:,:)
REAL(KIND=JPRB), POINTER          :: ZFLXZTKEMF  (:,:,:)
REAL(KIND=JPRB), POINTER          :: ZTHL_UP  (:,:,:) 
REAL(KIND=JPRB), POINTER          :: ZRT_UP  (:,:,:)  
REAL(KIND=JPRB), POINTER          :: ZRV_UP  (:,:,:)  
REAL(KIND=JPRB), POINTER          :: ZU_UP  (:,:,:)   
REAL(KIND=JPRB), POINTER          :: ZV_UP  (:,:,:)   
REAL(KIND=JPRB), POINTER          :: ZTKE_UP  (:,:,:)
REAL(KIND=JPRB), POINTER          :: ZRC_UP  (:,:,:)  
REAL(KIND=JPRB), POINTER          :: ZRI_UP  (:,:,:)  
REAL(KIND=JPRB), POINTER          :: ZTHV_UP  (:,:,:) 
REAL(KIND=JPRB), POINTER          :: ZW_UP  (:,:,:)   
REAL(KIND=JPRB), POINTER          :: ZFRAC_UP (:,:,:) 
REAL(KIND=JPRB), POINTER          :: ZEMF (:,:,:)     
REAL(KIND=JPRB), POINTER          :: ZDETR (:,:,:)    
REAL(KIND=JPRB), POINTER          :: ZENTR (:,:,:)    
INTEGER(KIND=JPIM), POINTER       :: IKLCL (:,:)
INTEGER(KIND=JPIM), POINTER       :: IKETL  (:,:)
INTEGER(KIND=JPIM), POINTER       :: IKCTL   (:,:)
REAL(KIND=JPRB)                   :: PDX, PDY
INTEGER(KIND=JPIM)                :: IGPBLKS
INTEGER(KIND=JPIM)                :: KBUDGETS     

#include "shallow_mf.intfb.h"

INTEGER :: JLON, JBLK
INTEGER :: ILUNCI, ILUNFI, ILUNFO, IOUT
INTEGER :: NPROMA, NGPBLKS,KLEV,KLON,KGPBLKS
CHARACTER (LEN=128) :: CLOUT
CHARACTER (LEN=128) :: CLCASE_IN
CHARACTER (LEN=128) :: CLCASE_OUT
TYPE (DD12), POINTER :: YLD
LOGICAL :: LLVERBOSE, LLDIFF
INTEGER, POINTER :: IBLOCKLIST (:)
TYPE(STACK) :: YLSTACK
INTEGER :: ISIZE4, ISIZE8
CHARACTER*64 :: CLMETHOD
INTEGER :: ITIME, NTIME
LOGICAL :: LLSAVE, LLEXIST
REAL(KIND=8) :: TSC, TEC, TSD, TED, ZTC, ZTD
#ifdef ARCH
CHARACTER (LEN=*), PARAMETER :: CLARCH = ARCH
#else
CHARACTER (LEN=*), PARAMETER :: CLARCH = 'unkwown'
#endif

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('MAIN_SHALLOW_MF', 0, ZHOOK_HANDLE)

YLD => NULL ()

CALL INITOPTIONS

NPROMA  = 0; CALL GETOPTION ("--nproma",  NPROMA)
NGPBLKS = 0; CALL GETOPTION ("--ngpblks", NGPBLKS)

CALL GETOPTION ("--case-in", CLCASE_IN, MND=.TRUE.)
CLCASE_OUT = ''; CALL GETOPTION ("--case-out", CLCASE_OUT)

CALL GETOPTION ("--verbose", LLVERBOSE)
CALL GETOPTION ("--diff", LLDIFF)
#ifdef PARKIND1_SINGLE
ISIZE4 = 80; 
ISIZE8 = 10; 
#else
ISIZE4 = 10; 
ISIZE8 = 80; 
#endif
CALL GETOPTION ("--stack-size-4", ISIZE4)
CALL GETOPTION ("--stack-size-8", ISIZE8)
NTIME = 1; CALL GETOPTION ("--times", NTIME)

CLMETHOD = 'openmp'; CALL GETOPTION ("--method", CLMETHOD)

IBLOCKLIST => NULL ()
CALL GETOPTION ("--block-list", IBLOCKLIST)

LLSAVE = CLCASE_OUT /= ''

IF (LLSAVE) THEN
  CALL XRD_MKDIR (TRIM (CLCASE_OUT))
ENDIF

CLOUT = '-'; CALL GETOPTION ("--out", CLOUT)

CALL CHECKOPTIONS
CALL LOADALL
IF (LLVERBOSE) THEN
WRITE (0, *) " NPROMA = ", NPROMA, " NGPBLKS = ", NGPBLKS, " KLEV = ", KLEV
WRITE (0, *) " ISIZE4 = ", ISIZE4, " ISIZE8 = ", ISIZE8, " NTIME = ", NTIME
ENDIF

IF (LLSAVE) THEN
  CALL SAVEIALL
ENDIF

CALL GET_TIME (TSD)

!$ACC DATA COPY ( ZZZ , ZDZZ,  ZRHODJ , ZRHODREF , ZPABSM    , ZEXNM     ,&
!$ACC& ZSFTH, ZSFRV, ZTHM, ZRM, ZUM, ZVM, ZTKEM, ZSVM, ZDUDT_MF, ZDVDT_MF,&
!$ACC& ZDTHLDT_MF, ZDRTDT_MF, ZDSVDT_MF, ZSIGMF, ZRC_MF, ZRI_MF, ZCF_MF,&
!$ACC& ZFLXZTHVMF, ZFLXZTHMF, ZFLXZRMF, ZFLXZUMF, ZFLXZVMF, ZTHL_UP, ZRT_UP,&
!$ACC& ZRV_UP, ZU_UP, ZV_UP, ZRC_UP, ZRI_UP, ZTHV_UP, ZW_UP, ZFRAC_UP, ZEMF,&
!$ACC& ZDETR, ZENTR, IKLCL, IKETL, IKCTL) IF (TRIM (CLMETHOD) == 'openaccsinglecolumn')

IF (TRIM (CLMETHOD) == 'openaccsinglecolumn') THEN
  CALL COPY (D)
  CALL COPY (DD)
  CALL COPY (CST)
  CALL COPY (NEBN)
  CALL COPY (PARAMMF)
  CALL COPY (TURBN)
  CALL COPY (CSTURB)
  CALL COPY (ICEP)
ENDIF

CALL GET_TIME (TSC)

DO ITIME = 1, NTIME

  IF (TRIM (CLMETHOD) == 'openmp') THEN

!$OMP PARALLEL DO PRIVATE (JBLK)
    DO JBLK = 1, NGPBLKS
      CALL SHALLOW_MF( &
          D, CST, NEBN, PARAMMF, TURBN, CSTURB,ICEP,            &
       &  KRR, KRRL, KRRI, KSV,                                 &
       &  ONOMIXLG,KSV_LGBEG,KSV_LGEND,                         &
       &  PTSTEP,                                               &
       &  ZDZZ(:,:,JBLK), ZZZ(:,:,JBLK),                                            &
       &  ZRHODJ(:,:,JBLK), ZRHODREF(:,:,JBLK),                                     &
       &  ZPABSM(:,:,JBLK), ZEXNM(:,:,JBLK),                                        &
       &  ZSFTH(:,JBLK),ZSFRV(:,JBLK),                                          &
       &  ZTHM(:,:,JBLK),ZRM(:,:,:,JBLK),ZUM(:,:,JBLK),&
       &  ZVM(:,:,JBLK),ZTKEM(:,:,JBLK),ZSVM(:,:,:,JBLK),                          &
       &  ZDUDT_MF(:,:,JBLK),ZDVDT_MF(:,:,JBLK),ZDTKEDT_MF(:,:,JBLK),               &
       &  ZDTHLDT_MF(:,:,JBLK),ZDRTDT_MF(:,:,JBLK),ZDSVDT_MF(:,:,:,JBLK),        &
       &  ZSIGMF(:,:,JBLK) ,ZRC_MF(:,:,JBLK),ZRI_MF(:,:,JBLK),                     &
       &  ZCF_MF(:,:,JBLK),ZHLC_HRC(:,:,JBLK),ZHLC_HCF(:,:,JBLK),               &
       &  ZHLI_HRI(:,:,JBLK),ZHLI_HCF(:,:,JBLK),                                &
       &  ZWEIGHT_MF_CLOUD(:,:,JBLK),ZFLXZTHVMF(:,:,JBLK),               &
       &  ZFLXZTHMF(:,:,JBLK),ZFLXZRMF(:,:,JBLK),ZFLXZUMF(:,:,JBLK),ZFLXZVMF(:,:,JBLK),&
       &  ZFLXZTKEMF(:,:,JBLK),ZTHL_UP(:,:,JBLK),ZRT_UP(:,:,JBLK),ZRV_UP(:,:,JBLK),&
       &  ZRC_UP(:,:,JBLK),ZRI_UP(:,:,JBLK),ZU_UP(:,:,JBLK),                  &
       &  ZV_UP(:,:,JBLK), ZTKE_UP(:,:,JBLK),ZTHV_UP(:,:,JBLK), ZW_UP(:,:,JBLK),     &
       &  ZFRAC_UP(:,:,JBLK),ZEMF(:,:,JBLK),ZDETR(:,:,JBLK),ZENTR(:,:,JBLK),        &
       &  IKLCL(:,JBLK),IKETL(:,JBLK),IKCTL(:,JBLK),PDX,PDY,                            &
       &  KBUDGETS=KBUDGETS                            )
    ENDDO

  ELSEIF (TRIM (CLMETHOD) == 'openmpsinglecolumn') THEN

    IF (ITIME==1) THEN
      YSTACK%IALIGN = 8 
      IF (ISIZE4 > 0) ALLOCATE (YSTACK%ZDATA4 (NPROMA, KLEV, ISIZE4, NGPBLKS))
      IF (ISIZE8 > 0) ALLOCATE (YSTACK%ZDATA8 (NPROMA, KLEV, ISIZE8, NGPBLKS))
    ENDIF
!$OMP PARALLEL DO PRIVATE (JBLK, JLON, YLSTACK) FIRSTPRIVATE(D) COLLAPSE(2)
    DO JBLK = 1, NGPBLKS
      DO JLON = 1,NPROMA
        D%NIJB=JLON
        D%NIJE=JLON
        D%NIB=JLON
        D%NIE=JLON
        YLSTACK%L8 = stack_l8 (YSTACK, JBLK, NGPBLKS)
        YLSTACK%U8 = stack_u8 (YSTACK, JBLK, NGPBLKS)
        YLSTACK%L4 = stack_l4 (YSTACK, JBLK, NGPBLKS)
        YLSTACK%U4 = stack_u4 (YSTACK, JBLK, NGPBLKS)
          
        CALL SHALLOW_MF_OPENACC(  D, CST, NEBN, PARAMMF, TURBN, CSTURB,ICEP,    &
       &  KRR, KRRL, KRRI, KSV,                                 &
       &  ONOMIXLG,KSV_LGBEG,KSV_LGEND,                         &
       &  PTSTEP,                                               &
       &  ZDZZ(:,:,JBLK), ZZZ(:,:,JBLK),                                            &
       &  ZRHODJ(:,:,JBLK), ZRHODREF(:,:,JBLK),                                     &
       &  ZPABSM(:,:,JBLK), ZEXNM(:,:,JBLK),                                        &
       &  ZSFTH(:,JBLK),ZSFRV(:,JBLK),                                          &
       &  ZTHM(:,:,JBLK),ZRM(:,:,:,JBLK),ZUM(:,:,JBLK),&
       &  ZVM(:,:,JBLK),ZTKEM(:,:,JBLK),ZSVM(:,:,:,JBLK),                          &
       &  ZDUDT_MF(:,:,JBLK),ZDVDT_MF(:,:,JBLK),ZDTKEDT_MF(:,:,JBLK),               &
       &  ZDTHLDT_MF(:,:,JBLK),ZDRTDT_MF(:,:,JBLK),ZDSVDT_MF(:,:,:,JBLK),        &
       &  ZSIGMF(:,:,JBLK) ,ZRC_MF(:,:,JBLK),ZRI_MF(:,:,JBLK),                     &
       &  ZCF_MF(:,:,JBLK),ZHLC_HRC(:,:,JBLK),ZHLC_HCF(:,:,JBLK),               &
       &  ZHLI_HRI(:,:,JBLK),ZHLI_HCF(:,:,JBLK),                                &
       &  ZWEIGHT_MF_CLOUD(:,:,JBLK),ZFLXZTHVMF(:,:,JBLK),               &
       &  ZFLXZTHMF(:,:,JBLK),ZFLXZRMF(:,:,JBLK),ZFLXZUMF(:,:,JBLK),ZFLXZVMF(:,:,JBLK),&
       &  ZFLXZTKEMF(:,:,JBLK),ZTHL_UP(:,:,JBLK),ZRT_UP(:,:,JBLK),ZRV_UP(:,:,JBLK),&
       &  ZRC_UP(:,:,JBLK),ZRI_UP(:,:,JBLK),ZU_UP(:,:,JBLK),                  &
       &  ZV_UP(:,:,JBLK), ZTKE_UP(:,:,JBLK),ZTHV_UP(:,:,JBLK), ZW_UP(:,:,JBLK),     &
       &  ZFRAC_UP(:,:,JBLK),ZEMF(:,:,JBLK),ZDETR(:,:,JBLK),ZENTR(:,:,JBLK),        &
       &  IKLCL(:,JBLK),IKETL(:,JBLK),IKCTL(:,JBLK),PDX,PDY,                            &
       &  KBUDGETS=KBUDGETS, YDSTACK=YLSTACK           )
      ENDDO
    
    ENDDO

  ELSEIF (TRIM (CLMETHOD) == 'openaccsinglecolumn') THEN

#ifdef __NVCOMPILER
CALL NVTXSTARTRANGE("SHALLOW_MF_OPENACC")
#endif


    IF (ITIME==1) THEN
      YSTACK%IALIGN = 8 
      ALLOCATE (YSTACK%ZDATA4 (NPROMA, KLEV, ISIZE4, NGPBLKS))
      ALLOCATE (YSTACK%ZDATA8 (NPROMA, KLEV, ISIZE8, NGPBLKS))

!$ACC ENTER DATA CREATE (YSTACK%ZDATA4)
!$ACC ENTER DATA CREATE (YSTACK%ZDATA8)

!$ACC ENTER DATA CREATE (YSTACK)
!$ACC UPDATE DEVICE (YSTACK)
!$ACC ENTER DATA ATTACH (YSTACK%ZDATA4)
!$ACC ENTER DATA ATTACH (YSTACK%ZDATA8)

    ENDIF
    
!$ACC PARALLEL LOOP GANG &
!$ACC&PRESENT (  ZZZ , ZDZZ,  ZRHODJ , ZRHODREF , ZPABSM    , ZEXNM     ,&
!$ACC& ZSFTH, ZSFRV, ZTHM, ZRM, ZUM, ZVM, ZTKEM, ZSVM, ZDUDT_MF, ZDVDT_MF,&
!$ACC& ZDTHLDT_MF, ZDRTDT_MF, ZDSVDT_MF, ZSIGMF, ZRC_MF, ZRI_MF, ZCF_MF,&
!$ACC& ZFLXZTHVMF, ZFLXZTHMF, ZFLXZRMF, ZFLXZUMF, ZFLXZVMF, ZTHL_UP, ZRT_UP,&
!$ACC& ZRV_UP, ZU_UP, ZV_UP, ZRC_UP, ZRI_UP, ZTHV_UP, ZW_UP, ZFRAC_UP, ZEMF,&
!$ACC& ZDETR, ZENTR, IKLCL, IKETL, IKCTL, D) &
!$ACC&PRIVATE (JBLK,DD) &
!$ACC&VECTOR_LENGTH (NPROMA)
   DO JBLK = 1, NGPBLKS
!$ACC LOOP VECTOR &
!$ACC&PRIVATE (JLON,DD, YLSTACK) 
    
      DO JLON = 1, NPROMA
        DD=D    
        DD%NIJB=JLON
        DD%NIJE=JLON
        DD%NIB=JLON
        DD%NIE=JLON
        YLSTACK%L8 = stack_l8 (YSTACK, JBLK, NGPBLKS)
        YLSTACK%U8 = stack_u8 (YSTACK, JBLK, NGPBLKS)
        YLSTACK%L4 = stack_l4 (YSTACK, JBLK, NGPBLKS)
        YLSTACK%U4 = stack_u4 (YSTACK, JBLK, NGPBLKS)

        CALL SHALLOW_MF_OPENACC( &
          DD, CST, NEBN, PARAMMF, TURBN, CSTURB,ICEP,            &
       &  KRR, KRRL, KRRI, KSV,                                 &
       &  ONOMIXLG,KSV_LGBEG,KSV_LGEND,                         &
       &  PTSTEP,                                               &
       &  ZDZZ(:,:,JBLK), ZZZ(:,:,JBLK),                                            &
       &  ZRHODJ(:,:,JBLK), ZRHODREF(:,:,JBLK),                                     &
       &  ZPABSM(:,:,JBLK), ZEXNM(:,:,JBLK),                                        &
       &  ZSFTH(:,JBLK),ZSFRV(:,JBLK),                                          &
       &  ZTHM(:,:,JBLK),ZRM(:,:,:,JBLK),ZUM(:,:,JBLK),&
       &  ZVM(:,:,JBLK),ZTKEM(:,:,JBLK),ZSVM(:,:,:,JBLK),                          &
       &  ZDUDT_MF(:,:,JBLK),ZDVDT_MF(:,:,JBLK),ZDTKEDT_MF(:,:,JBLK),               &
       &  ZDTHLDT_MF(:,:,JBLK),ZDRTDT_MF(:,:,JBLK),ZDSVDT_MF(:,:,:,JBLK),        &
       &  ZSIGMF(:,:,JBLK) ,ZRC_MF(:,:,JBLK),ZRI_MF(:,:,JBLK),                     &
       &  ZCF_MF(:,:,JBLK),ZHLC_HRC(:,:,JBLK),ZHLC_HCF(:,:,JBLK),               &
       &  ZHLI_HRI(:,:,JBLK),ZHLI_HCF(:,:,JBLK),                                &
       &  ZWEIGHT_MF_CLOUD(:,:,JBLK),ZFLXZTHVMF(:,:,JBLK),               &
       &  ZFLXZTHMF(:,:,JBLK),ZFLXZRMF(:,:,JBLK),ZFLXZUMF(:,:,JBLK),ZFLXZVMF(:,:,JBLK),&
       &  ZFLXZTKEMF(:,:,JBLK),ZTHL_UP(:,:,JBLK),ZRT_UP(:,:,JBLK),ZRV_UP(:,:,JBLK),&
       &  ZRC_UP(:,:,JBLK),ZRI_UP(:,:,JBLK),ZU_UP(:,:,JBLK),                  &
       &  ZV_UP(:,:,JBLK), ZTKE_UP(:,:,JBLK),ZTHV_UP(:,:,JBLK), ZW_UP(:,:,JBLK),     &
       &  ZFRAC_UP(:,:,JBLK),ZEMF(:,:,JBLK),ZDETR(:,:,JBLK),ZENTR(:,:,JBLK),        &
       &  IKLCL(:,JBLK),IKETL(:,JBLK),IKCTL(:,JBLK),PDX,PDY,                            &
       &  KBUDGETS=KBUDGETS, YDSTACK=YLSTACK           )
      ENDDO
    
    ENDDO

#ifdef __NVCOMPILER
CALL NVTXENDRANGE()
#endif

  ENDIF

ENDDO

CALL GET_TIME (TEC)

IF (TRIM (CLMETHOD) == 'openaccsinglecolumn') THEN
  CALL WIPE (D)
  CALL WIPE (CST)
  CALL WIPE (NEBN)
  CALL WIPE (PARAMMF)
  CALL WIPE (TURBN)
  CALL WIPE (CSTURB)
  CALL WIPE (ICEP)
ENDIF

!$ACC END DATA

CALL GET_TIME (TED)

ZTC = TEC - TSC
ZTD = TED - TSD

LLEXIST = .FALSE.

IF (CLOUT == '-') THEN
  IOUT = STDOUT
ELSE
  IOUT = 77
  INQUIRE (FILE=TRIM (CLOUT), EXIST=LLEXIST)
  IF (LLEXIST) THEN
    OPEN (IOUT, FILE=TRIM (CLOUT), FORM='FORMATTED', STATUS='OLD', POSITION='APPEND')
  ELSE
    OPEN (IOUT, FILE=TRIM (CLOUT), FORM='FORMATTED', STATUS='NEW')
  ENDIF
ENDIF

IF (.NOT. LLEXIST) &
WRITE (IOUT, '(A16,";",A32,";",A8,";",A8,";",A8,4(";",A20))') &
              & "CLARCH", "CLMETHOD", "NPROMA", "NGPBLKS", "NTIME", &
              & "ZTCTOT", "ZTC", "ZTDTOT", "ZTD"

WRITE (IOUT, '(A16,";",A32,";",I8,";",I8,";",I8,4(";",E20.10))') &
              & CLARCH,  TRIM (CLMETHOD), NPROMA, NGPBLKS, NTIME, &
              & ZTC, ZTC / REAL (NPROMA*NGPBLKS*NTIME, 8), &
              & ZTD, ZTD / REAL (NPROMA*NGPBLKS*NTIME, 8)

IF (IOUT /= STDOUT) THEN
  CLOSE (IOUT)
ENDIF


IF (LLDIFF) THEN
  CALL DIFFALL
ENDIF

IF (LLSAVE) THEN
  CALL SAVEOALL
ENDIF

IF (LHOOK) CALL DR_HOOK ('MAIN_SHALLOW_MF', 1, ZHOOK_HANDLE)

CONTAINS

SUBROUTINE LOADALL

ILUNCI = 77
ILUNFI = 78

OPEN (ILUNCI, NAME=TRIM (CLCASE_IN)//'/SHALLOW_MF.CONST.dat', FORM='UNFORMATTED')
OPEN (ILUNFI, NAME=TRIM (CLCASE_IN)//'/SHALLOW_MF.IN.dat',    FORM='UNFORMATTED')

CALL LOAD (D           , ILUNCI)
CALL LOAD (CST         , ILUNCI)
CALL LOAD (NEBN        , ILUNCI)
CALL LOAD (PARAMMF     , ILUNCI)
CALL LOAD (TURBN       , ILUNCI)
CALL LOAD (CSTURB      , ILUNCI)
CALL LOAD (ICEP        , ILUNCI)
CALL LOAD (ILUNCI, KRR         )
CALL LOAD (ILUNCI, KRRL        )
CALL LOAD (ILUNCI, KRRI        )
CALL LOAD (ILUNCI, KSV         )
CALL LOAD (ILUNCI, ONOMIXLG    )
CALL LOAD (ILUNCI, KSV_LGBEG   )
CALL LOAD (ILUNCI, KSV_LGEND   )
CALL LOAD (ILUNCI, PTSTEP      )
CALL LOAD (ILUNCI, PDX         )
CALL LOAD (ILUNCI, PDY         )
CALL LOAD (ILUNCI, IGPBLKS     )
CALL LOAD (ILUNCI, KBUDGETS    )

KLON=D%NIJE-D%NIJB+1
KGPBLKS=IGPBLKS
IF (NPROMA == 0) NPROMA = KLON
IF (NGPBLKS == 0) THEN
  IF (ASSOCIATED (IBLOCKLIST)) THEN
    NGPBLKS = SIZE (IBLOCKLIST)
  ELSE
    NGPBLKS = KGPBLKS
  ENDIF
ENDIF
KLEV=D%NKT !D%NKT

IF ((NPROMA /= KLON) .OR. (NGPBLKS /= KGPBLKS) .OR. ASSOCIATED (IBLOCKLIST)) THEN

  ALLOCATE (YLD)

  IF (ASSOCIATED (IBLOCKLIST)) THEN
    CALL YLD%INIT ([KLON, KGPBLKS], [NPROMA, NGPBLKS], IBLOCKLIST)
  ELSE
    CALL YLD%INIT ([KLON, KGPBLKS], [NPROMA, NGPBLKS])
  ENDIF
  
  NPROMA = YLD%IPROMA2
  NGPBLKS = YLD%IGPBLKS2

ENDIF

KLON = NPROMA
KGPBLKS = NGPBLKS
D%NIB=1
D%NIE=KLON
D%NIBC=1
D%NIEC=KLON
D%NIJB=1
D%NIJE=KLON
D%NIBC=1
D%NIEC=KLON
D%NIT=KLON
D%NIJT=KLON
CALL LOAD (ILUNFI,  ZZZ             , YDD=YLD)
CALL LOAD (ILUNFI,  ZDZZ            , YDD=YLD)
CALL LOAD (ILUNFI,  ZRHODJ          , YDD=YLD)
CALL LOAD (ILUNFI,  ZRHODREF        , YDD=YLD)
CALL LOAD (ILUNFI,  ZPABSM          , YDD=YLD)
CALL LOAD (ILUNFI,  ZEXNM           , YDD=YLD)
CALL LOAD (ILUNFI,  ZSFTH           , YDD=YLD)
CALL LOAD (ILUNFI,  ZSFRV           , YDD=YLD)
CALL LOAD (ILUNFI,  ZTHM            , YDD=YLD)
CALL LOAD (ILUNFI,  ZRM             , YDD=YLD)
CALL LOAD (ILUNFI,  ZUM             , YDD=YLD)
CALL LOAD (ILUNFI,  ZVM             , YDD=YLD)
CALL LOAD (ILUNFI,  ZTKEM           , YDD=YLD)
CALL LOAD (ILUNFI,  ZSVM            , YDD=YLD)
CALL LOAD (ILUNFI,  ZDUDT_MF        , YDD=YLD)
CALL LOAD (ILUNFI,  ZDVDT_MF        , YDD=YLD)
CALL LOAD (ILUNFI,  ZDTHLDT_MF      , YDD=YLD)
CALL LOAD (ILUNFI,  ZDRTDT_MF       , YDD=YLD)
CALL LOAD (ILUNFI,  ZDSVDT_MF       , YDD=YLD)
CALL LOAD (ILUNFI,  ZSIGMF          , YDD=YLD)
CALL LOAD (ILUNFI,  ZRC_MF          , YDD=YLD)
CALL LOAD (ILUNFI,  ZRI_MF          , YDD=YLD)
CALL LOAD (ILUNFI,  ZCF_MF          , YDD=YLD)
CALL LOAD (ILUNFI,  ZFLXZTHVMF      , YDD=YLD)
CALL LOAD (ILUNFI,  ZFLXZTHMF       , YDD=YLD)
CALL LOAD (ILUNFI,  ZFLXZRMF        , YDD=YLD)
CALL LOAD (ILUNFI,  ZFLXZUMF        , YDD=YLD)
CALL LOAD (ILUNFI,  ZFLXZVMF        , YDD=YLD)
CALL LOAD (ILUNFI,  ZTHL_UP         , YDD=YLD)
CALL LOAD (ILUNFI,  ZRT_UP          , YDD=YLD)
CALL LOAD (ILUNFI,  ZRV_UP          , YDD=YLD)
CALL LOAD (ILUNFI,  ZU_UP           , YDD=YLD)
CALL LOAD (ILUNFI,  ZV_UP           , YDD=YLD)
CALL LOAD (ILUNFI,  ZRC_UP          , YDD=YLD)
CALL LOAD (ILUNFI,  ZRI_UP          , YDD=YLD)
CALL LOAD (ILUNFI,  ZTHV_UP         , YDD=YLD)
CALL LOAD (ILUNFI,  ZW_UP           , YDD=YLD)
CALL LOAD (ILUNFI,  ZFRAC_UP        , YDD=YLD)
CALL LOAD (ILUNFI,  ZEMF            , YDD=YLD)
CALL LOAD (ILUNFI,  ZDETR           , YDD=YLD)
CALL LOAD (ILUNFI,  ZENTR           , YDD=YLD)
CALL LOAD (ILUNFI,  IKLCL           , YDD=YLD)
CALL LOAD (ILUNFI,  IKETL           , YDD=YLD)
CALL LOAD (ILUNFI,  IKCTL           , YDD=YLD)
CALL LOAD (ILUNFI,  ZDTKEDT_MF      , YDD=YLD)           
CALL LOAD (ILUNFI,  ZHLC_HRC       , YDD=YLD)          
CALL LOAD (ILUNFI,  ZHLC_HCF        , YDD=YLD)        
CALL LOAD (ILUNFI,  ZHLI_HRI        , YDD=YLD)         
CALL LOAD (ILUNFI,  ZHLI_HCF        , YDD=YLD)     
CALL LOAD (ILUNFI,  ZWEIGHT_MF_CLOUD, YDD=YLD) 
CALL LOAD (ILUNFI,  ZFLXZTKEMF      , YDD=YLD)       
CALL LOAD (ILUNFI,  ZTKE_UP         , YDD=YLD)         


                    
CLOSE (ILUNFI)      
CLOSE (ILUNCI)  
OPEN (ILUNFI, NAME=TRIM (CLCASE_IN)//'/SHALLOW_MF.IN.dat',    FORM='UNFORMATTED')
END SUBROUTINE

SUBROUTINE DIFFALL
IF (LLVERBOSE) PRINT *, " DIFF..."

ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/SHALLOW_MF.OUT.dat', FORM='UNFORMATTED')

CALL DIFF (" ZDUDT_MF  ",         ZDUDT_MF        , KLUN=ILUNFO, YDD=YLD)    
CALL DIFF (" ZDVDT_MF  ",         ZDVDT_MF        , KLUN=ILUNFO, YDD=YLD)   
CALL DIFF (" ZDTHLDT_MF",         ZDTHLDT_MF      , KLUN=ILUNFO, YDD=YLD)   
CALL DIFF (" ZDRTDT_MF ",         ZDRTDT_MF       , KLUN=ILUNFO, YDD=YLD)    
CALL DIFF (" ZDSVDT_MF ",         ZDSVDT_MF       , KLUN=ILUNFO, YDD=YLD)   
CALL DIFF (" ZSIGMF    ",         ZSIGMF          , KLUN=ILUNFO, YDD=YLD)    
CALL DIFF (" ZRC_MF    ",         ZRC_MF          , KLUN=ILUNFO, YDD=YLD)   
CALL DIFF (" ZRI_MF    ",         ZRI_MF          , KLUN=ILUNFO, YDD=YLD)        
CALL DIFF (" ZCF_MF    ",         ZCF_MF          , KLUN=ILUNFO, YDD=YLD)        
CALL DIFF (" ZFLXZTHVM ",         ZFLXZTHVMF      , KLUN=ILUNFO, YDD=YLD)          
CALL DIFF (" ZFLXZTHMF ",         ZFLXZTHMF       , KLUN=ILUNFO, YDD=YLD)   
CALL DIFF (" ZFLXZRMF  ",         ZFLXZRMF        , KLUN=ILUNFO, YDD=YLD)  
CALL DIFF (" ZFLXZUMF  ",         ZFLXZUMF        , KLUN=ILUNFO, YDD=YLD)  
CALL DIFF (" ZFLXZVMF  ",         ZFLXZVMF        , KLUN=ILUNFO, YDD=YLD)  
CALL DIFF (" ZTHL_UP   ",         ZTHL_UP         , KLUN=ILUNFO, YDD=YLD)    
CALL DIFF (" ZRT_UP    ",         ZRT_UP          , KLUN=ILUNFO, YDD=YLD)      
CALL DIFF (" ZRV_UP    ",         ZRV_UP          , KLUN=ILUNFO, YDD=YLD)   
CALL DIFF (" ZU_UP     ",         ZU_UP           , KLUN=ILUNFO, YDD=YLD)     
CALL DIFF (" ZV_UP     ",         ZV_UP           , KLUN=ILUNFO, YDD=YLD)     
CALL DIFF (" ZRC_UP    ",         ZRC_UP          , KLUN=ILUNFO, YDD=YLD)        
CALL DIFF (" ZRI_UP    ",         ZRI_UP          , KLUN=ILUNFO, YDD=YLD)        
CALL DIFF (" ZTHV_UP   ",         ZTHV_UP         , KLUN=ILUNFO, YDD=YLD)       
CALL DIFF (" ZW_UP     ",         ZW_UP           , KLUN=ILUNFO, YDD=YLD)       
CALL DIFF (" ZFRAC_UP  ",         ZFRAC_UP        , KLUN=ILUNFO, YDD=YLD)       
CALL DIFF (" ZEMF      ",         ZEMF            , KLUN=ILUNFO, YDD=YLD)     
CALL DIFF (" ZDETR     ",         ZDETR           , KLUN=ILUNFO, YDD=YLD)      
CALL DIFF (" ZENTR     ",         ZENTR           , KLUN=ILUNFO, YDD=YLD)      
CALL DIFF (" IKLCL     ",         IKLCL           , KLUN=ILUNFO, YDD=YLD)     
CALL DIFF (" IKETL     ",         IKETL           , KLUN=ILUNFO, YDD=YLD)      
CALL DIFF (" IKCTL     ",         IKCTL           , KLUN=ILUNFO, YDD=YLD)     
CALL DIFF (" ZDTKEDT_MF",         ZDTKEDT_MF      , KLUN=ILUNFO, YDD=YLD) 
CALL DIFF (" ZHLC_HRC  ",         ZHLC_HRC        , KLUN=ILUNFO, YDD=YLD)  
CALL DIFF (" ZHLC_HCF  ",         ZHLC_HCF        , KLUN=ILUNFO, YDD=YLD) 
CALL DIFF (" ZHLI_HRI  ",         ZHLI_HRI        , KLUN=ILUNFO, YDD=YLD) 
CALL DIFF (" ZHLI_HCF  ",         ZHLI_HCF        , KLUN=ILUNFO, YDD=YLD) 
CALL DIFF (" ZWEIGHT_MF_CLOUD",   ZWEIGHT_MF_CLOUD, KLUN=ILUNFO, YDD=YLD) 
CALL DIFF (" ZFLXZTKEMF",         ZFLXZTKEMF      , KLUN=ILUNFO, YDD=YLD) 
CALL DIFF (" ZTKE_UP   ",         ZTKE_UP         , KLUN=ILUNFO, YDD=YLD) 




 
CLOSE (ILUNFO)

IF (LLVERBOSE) PRINT *, " ...DIFF"

END SUBROUTINE

SUBROUTINE SAVEIALL

ILUNCI = 77
ILUNFI = 78

OPEN (ILUNCI, NAME=TRIM (CLCASE_OUT)//'/SHALLOW_MF.CONST.dat', FORM='UNFORMATTED')
OPEN (ILUNFI, NAME=TRIM (CLCASE_OUT)//'/SHALLOW_MF.IN.dat',    FORM='UNFORMATTED')

CALL SAVE ( D        ,ILUNCI) 
CALL SAVE ( CST      ,ILUNCI) 
CALL SAVE ( NEBN     ,ILUNCI) 
CALL SAVE ( PARAMMF  ,ILUNCI) 
CALL SAVE ( TURBN    ,ILUNCI) 
CALL SAVE ( CSTURB   ,ILUNCI)
CALL SAVE ( ICEP     ,ILUNCI)
CALL SAVE ( KRR      ,ILUNCI) 
CALL SAVE ( KRRL     ,ILUNCI) 
CALL SAVE ( KRRI     ,ILUNCI) 
CALL SAVE ( KSV      ,ILUNCI) 
CALL SAVE ( ONOMIXLG ,ILUNCI) 
CALL SAVE ( KSV_LGBEG,ILUNCI) 
CALL SAVE ( KSV_LGEND,ILUNCI) 
CALL SAVE ( PTSTEP   ,ILUNCI) 
CALL SAVE ( PDX      ,ILUNCI) 
CALL SAVE ( PDY      ,ILUNCI) 
CALL SAVE ( KGPBLKS  ,ILUNCI) 
CALL SAVE ( KBUDGETS  ,ILUNCI)
CALL SAVE (ZZZ       ,  ILUNFI, KLBOUND=LBOUND (ZZZ))
CALL SAVE (ZDZZ      ,  ILUNFI, KLBOUND=LBOUND (ZDZZ))
CALL SAVE (ZRHODJ    ,  ILUNFI, KLBOUND=LBOUND (ZRHODJ))
CALL SAVE (ZRHODREF  ,  ILUNFI, KLBOUND=LBOUND( ZRHODREF )) 
CALL SAVE (ZPABSM    ,  ILUNFI, KLBOUND=LBOUND( ZPABSM   )) 
CALL SAVE (ZEXNM     ,  ILUNFI, KLBOUND=LBOUND( ZEXNM    )) 
CALL SAVE (ZSFTH     ,  ILUNFI, KLBOUND=LBOUND( ZSFTH    )) 
CALL SAVE (ZSFRV     ,  ILUNFI, KLBOUND=LBOUND( ZSFRV    )) 
CALL SAVE (ZTHM      ,  ILUNFI, KLBOUND=LBOUND( ZTHM     )) 
CALL SAVE (ZRM       ,  ILUNFI, KLBOUND=LBOUND( ZRM      )) 
CALL SAVE (ZUM       ,  ILUNFI, KLBOUND=LBOUND( ZUM      )) 
CALL SAVE (ZVM       ,  ILUNFI, KLBOUND=LBOUND( ZVM      )) 
CALL SAVE (ZTKEM     ,  ILUNFI, KLBOUND=LBOUND( ZTKEM    )) 
CALL SAVE (ZSVM      ,  ILUNFI, KLBOUND=LBOUND( ZSVM     )) 
CALL SAVE (ZDUDT_MF  ,  ILUNFI, KLBOUND=LBOUND( ZDUDT_MF )) 
CALL SAVE (ZDVDT_MF  ,  ILUNFI, KLBOUND=LBOUND( ZDVDT_MF )) 
CALL SAVE (ZDTHLDT_MF,  ILUNFI, KLBOUND=LBOUND( ZDTHLDT_MF))
CALL SAVE (ZDRTDT_MF ,  ILUNFI, KLBOUND=LBOUND( ZDRTDT_MF)) 
CALL SAVE (ZDSVDT_MF ,  ILUNFI, KLBOUND=LBOUND( ZDSVDT_MF)) 
CALL SAVE (ZSIGMF    ,  ILUNFI, KLBOUND=LBOUND( ZSIGMF   )) 
CALL SAVE (ZRC_MF    ,  ILUNFI, KLBOUND=LBOUND( ZRC_MF   )) 
CALL SAVE (ZRI_MF    ,  ILUNFI, KLBOUND=LBOUND( ZRI_MF   )) 
CALL SAVE (ZCF_MF    ,  ILUNFI, KLBOUND=LBOUND( ZCF_MF   )) 
CALL SAVE (ZFLXZTHVMF,  ILUNFI, KLBOUND=LBOUND( ZFLXZTHVMF))
CALL SAVE (ZFLXZTHMF ,  ILUNFI, KLBOUND=LBOUND( ZFLXZTHMF)) 
CALL SAVE (ZFLXZRMF  ,  ILUNFI, KLBOUND=LBOUND( ZFLXZRMF )) 
CALL SAVE (ZFLXZUMF  ,  ILUNFI, KLBOUND=LBOUND( ZFLXZUMF )) 
CALL SAVE (ZFLXZVMF  ,  ILUNFI, KLBOUND=LBOUND( ZFLXZVMF )) 
CALL SAVE (ZTHL_UP   ,  ILUNFI, KLBOUND=LBOUND( ZTHL_UP  )) 
CALL SAVE (ZRT_UP    ,  ILUNFI, KLBOUND=LBOUND( ZRT_UP   )) 
CALL SAVE (ZRV_UP    ,  ILUNFI, KLBOUND=LBOUND( ZRV_UP   )) 
CALL SAVE (ZU_UP     ,  ILUNFI, KLBOUND=LBOUND( ZU_UP    )) 
CALL SAVE (ZV_UP     ,  ILUNFI, KLBOUND=LBOUND( ZV_UP    )) 
CALL SAVE (ZRC_UP    ,  ILUNFI, KLBOUND=LBOUND( ZRC_UP   )) 
CALL SAVE (ZRI_UP    ,  ILUNFI, KLBOUND=LBOUND( ZRI_UP   )) 
CALL SAVE (ZTHV_UP   ,  ILUNFI, KLBOUND=LBOUND( ZTHV_UP  )) 
CALL SAVE (ZW_UP     ,  ILUNFI, KLBOUND=LBOUND( ZW_UP    )) 
CALL SAVE (ZFRAC_UP  ,  ILUNFI, KLBOUND=LBOUND( ZFRAC_UP )) 
CALL SAVE (ZEMF      ,  ILUNFI, KLBOUND=LBOUND( ZEMF     )) 
CALL SAVE (ZDETR     ,  ILUNFI, KLBOUND=LBOUND( ZDETR    )) 
CALL SAVE (ZENTR     ,  ILUNFI, KLBOUND=LBOUND( ZENTR    )) 
CALL SAVE (IKLCL     ,  ILUNFI, KLBOUND=LBOUND( IKLCL    )) 
CALL SAVE (IKETL     ,  ILUNFI, KLBOUND=LBOUND( IKETL    )) 
CALL SAVE (IKCTL     ,  ILUNFI, KLBOUND=LBOUND( IKCTL    )) 
CALL SAVE (ZDTKEDT_MF      , ILUNFI, KLBOUND=LBOUND( ZDTKEDT_MF       ))           
CALL SAVE (ZHLC_HRC        , ILUNFI, KLBOUND=LBOUND( ZHLC_HRC         ))          
CALL SAVE (ZHLC_HCF        , ILUNFI, KLBOUND=LBOUND( ZHLC_HCF         ))        
CALL SAVE (ZHLI_HRI        , ILUNFI, KLBOUND=LBOUND( ZHLI_HRI         ))         
CALL SAVE (ZHLI_HCF        , ILUNFI, KLBOUND=LBOUND( ZHLI_HCF         ))     
CALL SAVE (ZWEIGHT_MF_CLOUD, ILUNFI, KLBOUND=LBOUND( ZWEIGHT_MF_CLOUD )) 
CALL SAVE (ZFLXZTKEMF      , ILUNFI, KLBOUND=LBOUND( ZFLXZTKEMF       ))       
CALL SAVE (ZTKE_UP         , ILUNFI, KLBOUND=LBOUND( ZTKE_UP          ))        

CLOSE (ILUNFI)
CLOSE (ILUNCI)  

END SUBROUTINE

SUBROUTINE SAVEOALL

ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_OUT)//'/SHALLOW_MF.OUT.dat', FORM='UNFORMATTED')
CALL SAVE(ZDUDT_MF   ,  ILUNFO,  KLBOUND=LBOUND( ZDUDT_MF )) 
CALL SAVE(ZDVDT_MF   ,  ILUNFO,  KLBOUND=LBOUND( ZDVDT_MF )) 
CALL SAVE(ZDTHLDT_MF ,  ILUNFO,  KLBOUND=LBOUND( ZDTHLDT_MF))
CALL SAVE(ZDRTDT_MF  ,  ILUNFO,  KLBOUND=LBOUND( ZDRTDT_MF)) 
CALL SAVE(ZDSVDT_MF  ,  ILUNFO,  KLBOUND=LBOUND( ZDSVDT_MF)) 
CALL SAVE(ZSIGMF     ,  ILUNFO,  KLBOUND=LBOUND( ZSIGMF   )) 
CALL SAVE(ZRC_MF     ,  ILUNFO,  KLBOUND=LBOUND( ZRC_MF   )) 
CALL SAVE(ZRI_MF     ,  ILUNFO,  KLBOUND=LBOUND( ZRI_MF   )) 
CALL SAVE(ZCF_MF     ,  ILUNFO,  KLBOUND=LBOUND( ZCF_MF   )) 
CALL SAVE(ZFLXZTHVMF ,  ILUNFO,  KLBOUND=LBOUND( ZFLXZTHVMF))
CALL SAVE(ZFLXZTHMF  ,  ILUNFO,  KLBOUND=LBOUND( ZFLXZTHMF)) 
CALL SAVE(ZFLXZRMF   ,  ILUNFO,  KLBOUND=LBOUND( ZFLXZRMF )) 
CALL SAVE(ZFLXZUMF   ,  ILUNFO,  KLBOUND=LBOUND( ZFLXZUMF )) 
CALL SAVE(ZFLXZVMF   ,  ILUNFO,  KLBOUND=LBOUND( ZFLXZVMF )) 
CALL SAVE(ZTHL_UP    ,  ILUNFO,  KLBOUND=LBOUND( ZTHL_UP  )) 
CALL SAVE(ZRT_UP     ,  ILUNFO,  KLBOUND=LBOUND( ZRT_UP   )) 
CALL SAVE(ZRV_UP     ,  ILUNFO,  KLBOUND=LBOUND( ZRV_UP   )) 
CALL SAVE(ZU_UP      ,  ILUNFO,  KLBOUND=LBOUND( ZU_UP    )) 
CALL SAVE(ZV_UP      ,  ILUNFO,  KLBOUND=LBOUND( ZV_UP    )) 
CALL SAVE(ZRC_UP     ,  ILUNFO,  KLBOUND=LBOUND( ZRC_UP   )) 
CALL SAVE(ZRI_UP     ,  ILUNFO,  KLBOUND=LBOUND( ZRI_UP   )) 
CALL SAVE(ZTHV_UP    ,  ILUNFO,  KLBOUND=LBOUND( ZTHV_UP  )) 
CALL SAVE(ZW_UP      ,  ILUNFO,  KLBOUND=LBOUND( ZW_UP    )) 
CALL SAVE(ZFRAC_UP   ,  ILUNFO,  KLBOUND=LBOUND( ZFRAC_UP )) 
CALL SAVE(ZEMF       ,  ILUNFO,  KLBOUND=LBOUND( ZEMF     )) 
CALL SAVE(ZDETR      ,  ILUNFO,  KLBOUND=LBOUND( ZDETR    )) 
CALL SAVE(ZENTR      ,  ILUNFO,  KLBOUND=LBOUND( ZENTR    )) 
CALL SAVE(IKLCL      ,  ILUNFO,  KLBOUND=LBOUND( IKLCL    )) 
CALL SAVE(IKETL      ,  ILUNFO,  KLBOUND=LBOUND( IKETL    )) 
CALL SAVE(IKCTL      ,  ILUNFO,  KLBOUND=LBOUND( IKCTL    )) 
CALL SAVE (ZDTKEDT_MF      , ILUNFO, KLBOUND=LBOUND( ZDTKEDT_MF       ))           
CALL SAVE (ZHLC_HRC        , ILUNFO, KLBOUND=LBOUND( ZHLC_HRC         ))          
CALL SAVE (ZHLC_HCF        , ILUNFO, KLBOUND=LBOUND( ZHLC_HCF         ))        
CALL SAVE (ZHLI_HRI        , ILUNFO, KLBOUND=LBOUND( ZHLI_HRI         ))         
CALL SAVE (ZHLI_HCF        , ILUNFO, KLBOUND=LBOUND( ZHLI_HCF         ))     
CALL SAVE (ZWEIGHT_MF_CLOUD, ILUNFO, KLBOUND=LBOUND( ZWEIGHT_MF_CLOUD )) 
CALL SAVE (ZFLXZTKEMF      , ILUNFO, KLBOUND=LBOUND( ZFLXZTKEMF       ))       
CALL SAVE (ZTKE_UP         , ILUNFO, KLBOUND=LBOUND( ZTKE_UP          ))       

CLOSE (ILUNFO)

END SUBROUTINE

END PROGRAM
