MODULE UTIL_DIMPHYEX_T_MOD

USE MODD_DIMPHYEX, ONLY : DIMPHYEX_T

INTERFACE SAVE
MODULE PROCEDURE SAVE_DIMPHYEX_T
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_DIMPHYEX_T
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_DIMPHYEX_T
END INTERFACE


     
INTERFACE CRC64
MODULE PROCEDURE CRC64_DIMPHYEX_T
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_DIMPHYEX_T
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_DIMPHYEX_T
END INTERFACE


CONTAINS

SUBROUTINE SAVE_DIMPHYEX_T (SELF, KLUN)

IMPLICIT NONE
TYPE (DIMPHYEX_T), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%NIT
WRITE (KLUN) SELF%NIB
WRITE (KLUN) SELF%NIE
WRITE (KLUN) SELF%NJT
WRITE (KLUN) SELF%NJB
WRITE (KLUN) SELF%NJE
WRITE (KLUN) SELF%NKL
WRITE (KLUN) SELF%NKT
WRITE (KLUN) SELF%NKLES
WRITE (KLUN) SELF%NKA
WRITE (KLUN) SELF%NKU
WRITE (KLUN) SELF%NKB
WRITE (KLUN) SELF%NKE
WRITE (KLUN) SELF%NKTB
WRITE (KLUN) SELF%NKTE
WRITE (KLUN) SELF%NIBC
WRITE (KLUN) SELF%NJBC
WRITE (KLUN) SELF%NIEC
WRITE (KLUN) SELF%NJEC
WRITE (KLUN) SELF%NIJT
WRITE (KLUN) SELF%NIJB
WRITE (KLUN) SELF%NIJE
WRITE (KLUN) SELF%NLESMASK
WRITE (KLUN) SELF%NLES_TIMES
END SUBROUTINE

SUBROUTINE LOAD_DIMPHYEX_T (SELF, KLUN)

IMPLICIT NONE
TYPE (DIMPHYEX_T), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%NIT
READ (KLUN) SELF%NIB
READ (KLUN) SELF%NIE
READ (KLUN) SELF%NJT
READ (KLUN) SELF%NJB
READ (KLUN) SELF%NJE
READ (KLUN) SELF%NKL
READ (KLUN) SELF%NKT
READ (KLUN) SELF%NKLES
READ (KLUN) SELF%NKA
READ (KLUN) SELF%NKU
READ (KLUN) SELF%NKB
READ (KLUN) SELF%NKE
READ (KLUN) SELF%NKTB
READ (KLUN) SELF%NKTE
READ (KLUN) SELF%NIBC
READ (KLUN) SELF%NJBC
READ (KLUN) SELF%NIEC
READ (KLUN) SELF%NJEC
READ (KLUN) SELF%NIJT
READ (KLUN) SELF%NIJB
READ (KLUN) SELF%NIJE
READ (KLUN) SELF%NLESMASK
READ (KLUN) SELF%NLES_TIMES
END SUBROUTINE


SUBROUTINE COPY_DIMPHYEX_T (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (DIMPHYEX_T), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE



     

SUBROUTINE CRC64_DIMPHYEX_T (SELF, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (DIMPHYEX_T), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NIT), CDPATH//'%NIT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NIB), CDPATH//'%NIB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NIE), CDPATH//'%NIE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NJT), CDPATH//'%NJT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NJB), CDPATH//'%NJB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NJE), CDPATH//'%NJE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NKL), CDPATH//'%NKL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NKT), CDPATH//'%NKT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NKLES), CDPATH//'%NKLES'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NKA), CDPATH//'%NKA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NKU), CDPATH//'%NKU'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NKB), CDPATH//'%NKB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NKE), CDPATH//'%NKE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NKTB), CDPATH//'%NKTB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NKTE), CDPATH//'%NKTE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NIBC), CDPATH//'%NIBC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NJBC), CDPATH//'%NJBC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NIEC), CDPATH//'%NIEC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NJEC), CDPATH//'%NJEC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NIJT), CDPATH//'%NIJT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NIJB), CDPATH//'%NIJB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NIJE), CDPATH//'%NIJE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NLESMASK), CDPATH//'%NLESMASK'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NLES_TIMES), CDPATH//'%NLES_TIMES'

END SUBROUTINE

SUBROUTINE WIPE_DIMPHYEX_T (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (DIMPHYEX_T), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

FUNCTION SIZE_DIMPHYEX_T (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (DIMPHYEX_T),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%NIT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NIT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NIB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NIB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NIE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NIE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NJT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NJT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NJB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NJB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NJE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NJE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NKL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NKL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NKT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NKT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NKLES)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NKLES'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NKA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NKA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NKU)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NKU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NKB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NKB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NKE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NKE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NKTB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NKTB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NKTE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NKTE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NIBC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NIBC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NJBC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NJBC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NIEC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NIEC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NJEC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NJEC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NIJT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NIJT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NIJB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NIJB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NIJE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NIJE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NLESMASK)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NLESMASK'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NLES_TIMES)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NLES_TIMES'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
