MODULE UTIL_TIWMX_T_MOD

USE MODD_TIWMX, ONLY : TIWMX_T

INTERFACE SAVE
MODULE PROCEDURE SAVE_TIWMX_T
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TIWMX_T
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TIWMX_T
END INTERFACE


     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TIWMX_T
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TIWMX_T
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TIWMX_T
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TIWMX_T (SELF, KLUN)

IMPLICIT NONE
TYPE (TIWMX_T), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%ESTABW
WRITE (KLUN) SELF%DESTABW
WRITE (KLUN) SELF%ESTABI
WRITE (KLUN) SELF%DESTABI
WRITE (KLUN) SELF%A2TAB
WRITE (KLUN) SELF%BB3TAB
WRITE (KLUN) SELF%AM3TAB
WRITE (KLUN) SELF%AF3TAB
WRITE (KLUN) SELF%A2WTAB
WRITE (KLUN) SELF%BB3WTAB
WRITE (KLUN) SELF%REDINTAB
END SUBROUTINE

SUBROUTINE LOAD_TIWMX_T (SELF, KLUN)

IMPLICIT NONE
TYPE (TIWMX_T), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%ESTABW
READ (KLUN) SELF%DESTABW
READ (KLUN) SELF%ESTABI
READ (KLUN) SELF%DESTABI
READ (KLUN) SELF%A2TAB
READ (KLUN) SELF%BB3TAB
READ (KLUN) SELF%AM3TAB
READ (KLUN) SELF%AF3TAB
READ (KLUN) SELF%A2WTAB
READ (KLUN) SELF%BB3WTAB
READ (KLUN) SELF%REDINTAB
END SUBROUTINE


SUBROUTINE COPY_TIWMX_T (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TIWMX_T), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE



     

SUBROUTINE CRC64_TIWMX_T (SELF, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (TIWMX_T), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ESTABW), CDPATH//'%ESTABW'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%DESTABW), CDPATH//'%DESTABW'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ESTABI), CDPATH//'%ESTABI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%DESTABI), CDPATH//'%DESTABI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%A2TAB), CDPATH//'%A2TAB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%BB3TAB), CDPATH//'%BB3TAB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%AM3TAB), CDPATH//'%AM3TAB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%AF3TAB), CDPATH//'%AF3TAB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%A2WTAB), CDPATH//'%A2WTAB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%BB3WTAB), CDPATH//'%BB3WTAB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%REDINTAB), CDPATH//'%REDINTAB'

END SUBROUTINE

SUBROUTINE WIPE_TIWMX_T (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TIWMX_T), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

FUNCTION SIZE_TIWMX_T (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TIWMX_T),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%ESTABW) * SIZE (SELF%ESTABW)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ESTABW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%DESTABW) * SIZE (SELF%DESTABW)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%DESTABW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ESTABI) * SIZE (SELF%ESTABI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ESTABI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%DESTABI) * SIZE (SELF%DESTABI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%DESTABI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%A2TAB) * SIZE (SELF%A2TAB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%A2TAB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%BB3TAB) * SIZE (SELF%BB3TAB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%BB3TAB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%AM3TAB) * SIZE (SELF%AM3TAB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%AM3TAB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%AF3TAB) * SIZE (SELF%AF3TAB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%AF3TAB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%A2WTAB) * SIZE (SELF%A2WTAB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%A2WTAB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%BB3WTAB) * SIZE (SELF%BB3WTAB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%BB3WTAB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%REDINTAB) * SIZE (SELF%REDINTAB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%REDINTAB'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
